import SteepestDescentScalingLaws.Commons
import SteepestDescentScalingLaws.StarConvexScalingLawsTheorem1
import SteepestDescentScalingLaws.StarConvexScalingLawsTheorem2
import SteepestDescentScalingLaws.FWExpectedGapSLTheorem1
import SteepestDescentScalingLaws.FWExpectedGapSLTheorem2
import SteepestDescentScalingLaws.FWExpectedSuboptimalitySLTheorem1
import SteepestDescentScalingLaws.FWExpectedSuboptimalitySLTheorem2
