import SteepestDescentOptimizationBounds.Assumptions
import SteepestDescentOptimizationBounds.DescentLemma
import SteepestDescentOptimizationBounds.MinibatchNoise
import SteepestDescentOptimizationBounds.WeightAndUpdateBounds
import SteepestDescentOptimizationBounds.MomentumBounds
import SteepestDescentOptimizationBounds.NesterovMomentumBounds
import SteepestDescentOptimizationBounds.Theorem14
import SteepestDescentOptimizationBounds.ExpectedSuboptimalityConvergence
