import Mathlib
import MlOptBoundsFormalization.Assumptions
import MlOptBoundsFormalization.DescentLemma

open scoped BigOperators

namespace MlOptBoundsFormalization

noncomputable section

open MeasureTheory
open ProbabilityTheory

variable {Ω V VDual : Type*}
variable [mΩ : MeasurableSpace Ω]
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [NormedAddCommGroup VDual] [NormedSpace ℝ VDual]

section NaturalNoise

variable [MeasurableSpace VDual] [BorelSpace VDual]

/-- The natural filtration generated by a sequence of `VDual`-valued noises. -/
def naturalNoiseFiltration
    {ξ : ℕ → Ω → VDual} (hξ : ∀ i, StronglyMeasurable (ξ i)) :
    Filtration ℕ (inferInstanceAs (MeasurableSpace Ω)) :=
  Filtration.natural (β := fun _ : ℕ => VDual) ξ hξ

/--
For an independent noise family, the conditional expectation of a future noise
term with respect to the natural filtration of the past is zero as soon as that
noise term has mean zero.
-/
theorem centered_noise_condexp_natural_ae_eq_zero
    [CompleteSpace VDual] [SecondCountableTopology VDual]
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual}
    (hξ : ∀ i, StronglyMeasurable (ξ i))
    (hIndep : iIndepFun ξ μ)
    {i j : ℕ} (hij : i < j)
    (hMeanZero : ∫ ω, ξ j ω ∂μ = 0) :
    μ[ξ j | naturalNoiseFiltration hξ i] =ᵐ[μ] 0 := by
  simpa [naturalNoiseFiltration, hMeanZero] using
    (iIndepFun.condExp_natural_ae_eq_of_lt (μ := μ) hξ hIndep hij)

end NaturalNoise

section

set_option linter.unusedSectionVars false

/--
If a scalar-valued cross term is obtained by applying an
`m`-measurable continuous linear functional to a noise term whose conditional
expectation given `m` vanishes, then the cross term has zero expectation.
-/
theorem integral_clm_apply_eq_zero_of_condexp_zero
    [NormedAddCommGroup VDual] [NormedSpace ℝ VDual]
    [CompleteSpace VDual]
    {μ : Measure Ω} {m : MeasurableSpace Ω}
    (hm : m ≤ mΩ)
    [IsFiniteMeasure μ]
    {L : Ω → VDual →L[ℝ] ℝ} {ξ : Ω → VDual}
    (hL : AEStronglyMeasurable[m] L μ)
    (hLξ : Integrable (fun ω => L ω (ξ ω)) μ)
    (hξ : Integrable ξ μ)
    (hCondZero : μ[ξ | m] =ᵐ[μ] 0) :
    ∫ ω, L ω (ξ ω) ∂μ = 0 := by
  let B : (VDual →L[ℝ] ℝ) →L[ℝ] VDual →L[ℝ] ℝ :=
    ContinuousLinearMap.flip
      (ContinuousLinearMap.apply ℝ ℝ : VDual →L[ℝ] (VDual →L[ℝ] ℝ) →L[ℝ] ℝ)
  have hPull :
      μ[fun ω ↦ L ω (ξ ω) | m] =ᵐ[μ] fun ω ↦ L ω (μ[ξ | m] ω) := by
    simpa [B] using
      (MeasureTheory.condExp_bilin_of_aestronglyMeasurable_left
        (μ := μ) (m := m) B hL (by simpa [B] using hLξ) hξ)
  have hCondCrossZero : μ[fun ω ↦ L ω (ξ ω) | m] =ᵐ[μ] 0 := by
    refine hPull.trans ?_
    filter_upwards [hCondZero] with ω hω
    simp [hω]
  calc
    ∫ ω, L ω (ξ ω) ∂μ = ∫ ω, (μ[fun ω ↦ L ω (ξ ω) | m]) ω ∂μ := by
      symm
      exact MeasureTheory.integral_condExp (μ := μ) (m := m) (f := fun ω ↦ L ω (ξ ω)) hm
    _ = ∫ ω, (0 : ℝ) ∂μ := integral_congr_ae hCondCrossZero
    _ = 0 := by simp

end

section NaturalNoise

variable [MeasurableSpace VDual] [BorelSpace VDual]

end NaturalNoise

/--
On a probability space, the first moment of `‖X‖` is bounded by the square root
of its second moment.
-/
theorem integral_norm_le_sqrt_second_moment
    {E : Type*} [NormedAddCommGroup E]
    {μ : Measure Ω} [IsProbabilityMeasure μ] {f : Ω → E}
    (hSq : Integrable (fun ω => ‖f ω‖ ^ 2) μ) :
    ∫ ω, ‖f ω‖ ∂μ ≤ Real.sqrt (∫ ω, ‖f ω‖ ^ 2 ∂μ) := by
  let g : Ω → ℝ := fun ω => ‖f ω‖
  have hgAesm : AEStronglyMeasurable g μ := by
    have hSqAesm : AEStronglyMeasurable (fun ω => ‖f ω‖ ^ 2) μ := hSq.aestronglyMeasurable
    have hSqrtAesm :
        AEStronglyMeasurable (fun ω => Real.sqrt (‖f ω‖ ^ 2)) μ :=
      hSqAesm.aemeasurable.sqrt.aestronglyMeasurable
    refine AEStronglyMeasurable.congr hSqrtAesm ?_
    filter_upwards with ω
    simp [g]
  have hgMemLp : MemLp g 2 μ := by
    refine (memLp_two_iff_integrable_sq hgAesm).2 ?_
    simpa [g] using hSq
  have hNormMemLp : MemLp (fun ω => ‖f ω‖) (ENNReal.ofReal 2) μ := by
    simpa [g] using hgMemLp
  have hOneMemLp : MemLp (fun _ : Ω => (1 : ℝ)) (ENNReal.ofReal 2) μ := by
    simpa using (memLp_const 1 : MemLp (fun _ : Ω => (1 : ℝ)) 2 μ)
  have hHolder :=
    integral_mul_le_Lp_mul_Lq_of_nonneg
      (μ := μ) (p := 2) (q := 2) Real.HolderConjugate.two_two
      (Filter.Eventually.of_forall fun ω => norm_nonneg (f ω))
      (Filter.Eventually.of_forall fun _ => show (0 : ℝ) ≤ 1 by norm_num)
      hNormMemLp hOneMemLp
  calc
    ∫ ω, ‖f ω‖ ∂μ = ∫ ω, g ω * 1 ∂μ := by simp [g]
    _ ≤
        (∫ ω, g ω ^ (2 : ℝ) ∂μ) ^ (1 / (2 : ℝ))
          * (∫ ω, (1 : ℝ) ^ (2 : ℝ) ∂μ) ^ (1 / (2 : ℝ)) := hHolder
    _ = (∫ ω, ‖f ω‖ ^ 2 ∂μ) ^ (1 / (2 : ℝ)) := by simp [g]
    _ = Real.sqrt (∫ ω, ‖f ω‖ ^ 2 ∂μ) := by rw [Real.sqrt_eq_rpow]

section WeightedNoiseCore

variable {Ω V VDual : Type*}
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [NormedAddCommGroup VDual] [NormedSpace ℝ VDual]

/-- Weighted partial sum used in the generic Lemma-5 minibatch estimates. -/
def weightedPartialSum
    (α : ℕ → ℝ) (ξ : ℕ → Ω → VDual) (k : ℕ) (ω : Ω) : VDual :=
  Finset.sum (Finset.range k) (fun i => α i • ξ i ω)

/-- A weighted finite sum of centered integrable noises still has mean zero. -/
theorem weightedPartialSum_mean_zero
    [MeasurableSpace Ω]
    {μ : Measure Ω}
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ}
    (sample_integrable : ∀ k, k < n → Integrable (ξ k) μ)
    (sample_mean_zero : ∀ k, k < n → ∫ ω, ξ k ω ∂μ = 0) :
    ∫ ω, weightedPartialSum α ξ n ω ∂μ = 0 := by
  calc
    ∫ ω, weightedPartialSum α ξ n ω ∂μ
      = ∫ ω, Finset.sum (Finset.range n) (fun i => α i • ξ i ω) ∂μ := by
          rfl
    _ 
      = Finset.sum (Finset.range n) (fun i => ∫ ω, α i • ξ i ω ∂μ) := by
          rw [MeasureTheory.integral_finset_sum]
          intro i hi
          exact (sample_integrable i (Finset.mem_range.mp hi)).smul (α i)
    _ = Finset.sum (Finset.range n) (fun _ => (0 : VDual)) := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          rw [MeasureTheory.integral_smul, sample_mean_zero i (Finset.mem_range.mp hi)]
          simp
    _ = 0 := by simp

private theorem weightedPartialSum_norm_le_noiseRadius_of_mem
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    {ω : Ω}
    (sample_norm_le_noiseRadius : ∀ i < n, ‖ξ i ω‖ ≤ B.noiseRadius) :
    ∀ k, k ≤ n → ‖weightedPartialSum α ξ k ω‖ ≤ B.noiseRadius := by
  intro k hk
  exact
    norm_sum_range_smul_le_of_nonneg_prefix
      hk coeff_nonneg coeff_sum_le_one sample_norm_le_noiseRadius B.noiseRadius_nonneg

private theorem weighted_smooth_step
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1) :
    ∀ k, k < n →
      ∀ ω,
      (∀ i, i < n → ‖ξ i ω‖ ≤ B.noiseRadius) →
        B.potential (weightedPartialSum α ξ (k + 1) ω) ≤
          B.potential (weightedPartialSum α ξ k ω)
            + α k
                * P.toLinear
                    (B.mirrorMap (weightedPartialSum α ξ k ω))
                    (ξ k ω)
            + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 := by
  intro k hk ω hξ
  let x : VDual := weightedPartialSum α ξ k ω
  have hx :
      ‖x‖ ≤ B.noiseRadius := by
    exact weightedPartialSum_norm_le_noiseRadius_of_mem P B coeff_nonneg coeff_sum_le_one
      (fun i hi => hξ i hi) k (Nat.le_of_lt hk)
  have hNext :
      ‖x + α k • ξ k ω‖ ≤ B.noiseRadius := by
    have hNext' :=
      weightedPartialSum_norm_le_noiseRadius_of_mem P B coeff_nonneg coeff_sum_le_one
        (fun i hi => hξ i hi) (k + 1) (Nat.succ_le_of_lt hk)
    simpa [weightedPartialSum, x, Finset.sum_range_succ, add_comm, add_left_comm, add_assoc] using hNext'
  have h :=
    step_upper_of_LSmoothOnClosedBallUnderPair
      P
      (f := B.potential)
      (grad := B.mirrorMap)
      (L := B.D)
      (R := B.noiseRadius)
      (α := α k)
      B.potential_fderiv_eq
      B.mirrorMap_local_lipschitz
      B.D_nonneg
      (coeff_nonneg k hk)
      hx
      hNext
  simpa [weightedPartialSum, x, Finset.sum_range_succ, add_comm, add_left_comm, add_assoc] using h

end WeightedNoiseCore

section WeightedNoiseFiltration

variable {Ω VDual : Type*}
variable [MeasurableSpace Ω]
variable [NormedAddCommGroup VDual]
variable [MeasurableSpace VDual] [BorelSpace VDual]

private lemma weighted_sampleStronglyMeasurable_mono_filtration
    {ξ : ℕ → Ω → VDual}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (i k : ℕ) (hik : i ≤ k) :
    StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k] (ξ i) := by
  exact
    ((Filtration.stronglyAdapted_natural
        (u := ξ) (hum := sample_stronglyMeasurable) i)).mono
      (show naturalNoiseFiltration sample_stronglyMeasurable i ≤
          naturalNoiseFiltration sample_stronglyMeasurable k from
        (naturalNoiseFiltration sample_stronglyMeasurable).mono hik)

private lemma weighted_partialSum_stronglyMeasurable
    [NormedSpace ℝ VDual]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i)) :
    ∀ k,
      StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k]
        (fun ω => weightedPartialSum α ξ (k + 1) ω)
  | 0 => by
      simpa [weightedPartialSum] using
        (weighted_sampleStronglyMeasurable_mono_filtration sample_stronglyMeasurable 0 0 le_rfl).const_smul
          (α 0)
  | k + 1 => by
      have hPrev :
          StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k]
            (fun ω => weightedPartialSum α ξ (k + 1) ω) :=
        weighted_partialSum_stronglyMeasurable sample_stronglyMeasurable k
      have hPrev' :
          StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable (k + 1)]
            (fun ω => weightedPartialSum α ξ (k + 1) ω) :=
        hPrev.mono (show naturalNoiseFiltration sample_stronglyMeasurable k ≤
            naturalNoiseFiltration sample_stronglyMeasurable (k + 1) from
          (naturalNoiseFiltration sample_stronglyMeasurable).mono (Nat.le_succ k))
      have hCurr :
          StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable (k + 1)]
            (fun ω => α (k + 1) • ξ (k + 1) ω) := by
        simpa using
          (weighted_sampleStronglyMeasurable_mono_filtration sample_stronglyMeasurable
            (k + 1) (k + 1) le_rfl).const_smul (α (k + 1))
      convert hPrev'.add hCurr using 1
      ext ω
      simp [weightedPartialSum, Finset.sum_range_succ, add_left_comm, add_comm]

end WeightedNoiseFiltration

section WeightedNoiseStronglyMeasurable

variable {Ω VDual : Type*}
variable [MeasurableSpace Ω]
variable [NormedAddCommGroup VDual]

private lemma weighted_partialSum_stronglyMeasurable_any
    [NormedSpace ℝ VDual]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i)) :
    ∀ k, StronglyMeasurable (fun ω => weightedPartialSum α ξ k ω)
  | 0 => by
      simpa [weightedPartialSum] using
        (stronglyMeasurable_const : StronglyMeasurable (fun _ : Ω => (0 : VDual)))
  | k + 1 => by
      have hk : StronglyMeasurable (fun ω => weightedPartialSum α ξ k ω) :=
        weighted_partialSum_stronglyMeasurable_any sample_stronglyMeasurable k
      have hCurr :
          StronglyMeasurable (fun ω => α k • ξ k ω) := by
        simpa using (sample_stronglyMeasurable k).const_smul (α k)
      convert hk.add hCurr using 1
      ext ω
      simp [weightedPartialSum, Finset.sum_range_succ, add_comm]

private theorem integrable_norm_mul_of_sq_integrable
    {μ : Measure Ω} {f g : Ω → VDual}
    (hf : StronglyMeasurable f)
    (hg : StronglyMeasurable g)
    (hf_sq : Integrable (fun ω => ‖f ω‖ ^ 2) μ)
    (hg_sq : Integrable (fun ω => ‖g ω‖ ^ 2) μ) :
    Integrable (fun ω => ‖f ω‖ * ‖g ω‖) μ := by
  have hMeas :
      AEStronglyMeasurable (fun ω => ‖f ω‖ * ‖g ω‖) μ := by
    exact (hf.norm.mul hg.norm).aestronglyMeasurable
  have hDom :
      Integrable (fun ω => ((‖f ω‖ ^ 2 + ‖g ω‖ ^ 2) / 2)) μ := by
    simpa [div_eq_mul_inv, Pi.add_apply, add_mul, mul_add, mul_assoc, mul_left_comm, mul_comm]
      using (hf_sq.add hg_sq).const_mul (1 / 2 : ℝ)
  refine Integrable.mono' hDom hMeas ?_
  filter_upwards with ω
  have hYoung : ‖f ω‖ * ‖g ω‖ ≤ (‖f ω‖ ^ 2 + ‖g ω‖ ^ 2) / 2 := by
    nlinarith [sq_nonneg (‖f ω‖ - ‖g ω‖)]
  have hLeftNonneg : 0 ≤ ‖f ω‖ * ‖g ω‖ :=
    mul_nonneg (norm_nonneg _) (norm_nonneg _)
  have hRightNonneg : 0 ≤ (‖f ω‖ ^ 2 + ‖g ω‖ ^ 2) / 2 := by
    positivity
  simpa [Real.norm_of_nonneg hLeftNonneg, Real.norm_of_nonneg hRightNonneg] using hYoung

end WeightedNoiseStronglyMeasurable

section WeightedNoise

variable {Ω V VDual : Type*}
variable [MeasurableSpace Ω]
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [NormedAddCommGroup VDual] [NormedSpace ℝ VDual]
variable [MeasurableSpace VDual] [BorelSpace VDual]
variable [SecondCountableTopology VDual] [CompleteSpace VDual]

section

set_option linter.unusedSectionVars false

private theorem weighted_crossTermCoefficient_aestronglyMeasurable
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (k : ℕ) :
    AEStronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k]
      (fun ω =>
        P.toLinear
          (B.mirrorMap (weightedPartialSum α ξ (k + 1) ω))) μ := by
  have hPartial :
      StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k]
        (fun ω => weightedPartialSum α ξ (k + 1) ω) :=
    weighted_partialSum_stronglyMeasurable sample_stronglyMeasurable k
  have hMirror :
      StronglyMeasurable[naturalNoiseFiltration sample_stronglyMeasurable k]
        (fun ω =>
          B.mirrorMap (weightedPartialSum α ξ (k + 1) ω)) :=
    B.mirrorMap_continuous.comp_stronglyMeasurable hPartial
  exact
    (P.toLinear.continuous.comp_stronglyMeasurable hMirror).aestronglyMeasurable

private theorem sample_norm_le_noiseRadius_all_ae
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {n : ℕ}
    (sample_norm_le_noiseRadius_ae :
      ∀ i, i < n → ∀ᵐ ω ∂μ, ‖ξ i ω‖ ≤ B.noiseRadius) :
    ∀ᵐ ω ∂μ, ∀ i, i < n → ‖ξ i ω‖ ≤ B.noiseRadius := by
  induction' n with n ih
  · exact Filter.Eventually.of_forall (by
      intro ω i hi
      exact (Nat.not_lt_zero _ hi).elim)
  · have hPrev :
        ∀ᵐ ω ∂μ, ∀ i, i < n → ‖ξ i ω‖ ≤ B.noiseRadius := by
      refine ih ?_
      intro i hi
      exact sample_norm_le_noiseRadius_ae i (Nat.lt_trans hi (Nat.lt_succ_self n))
    have hLast : ∀ᵐ ω ∂μ, ‖ξ n ω‖ ≤ B.noiseRadius :=
      sample_norm_le_noiseRadius_ae n (Nat.lt_succ_self n)
    filter_upwards [hPrev, hLast] with ω hPrevω hLastω
    intro i hi
    rcases Nat.lt_or_eq_of_le (Nat.le_of_lt_succ hi) with hi' | rfl
    · exact hPrevω i hi'
    · exact hLastω

private theorem weightedPartialSum_norm_le_noiseRadius_ae
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    (sample_norm_le_noiseRadius_ae :
      ∀ i, i < n → ∀ᵐ ω ∂μ, ‖ξ i ω‖ ≤ B.noiseRadius) :
    ∀ k, k ≤ n → ∀ᵐ ω ∂μ, ‖weightedPartialSum α ξ k ω‖ ≤ B.noiseRadius := by
  intro k hk
  have hAll :=
    sample_norm_le_noiseRadius_all_ae
      (B := B) (μ := μ) (ξ := ξ) (n := n) sample_norm_le_noiseRadius_ae
  filter_upwards [hAll] with ω hω
  exact
    weightedPartialSum_norm_le_noiseRadius_of_mem
      P B coeff_nonneg coeff_sum_le_one
      (fun i hi => hω i hi) k hk

private theorem weighted_smooth_step_ae
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    (sample_norm_le_noiseRadius_ae :
      ∀ i, i < n → ∀ᵐ ω ∂μ, ‖ξ i ω‖ ≤ B.noiseRadius) :
    ∀ k, k < n → ∀ᵐ ω ∂μ,
      B.potential (weightedPartialSum α ξ (k + 1) ω) ≤
        B.potential (weightedPartialSum α ξ k ω)
          + α k
              * P.toLinear
                  (B.mirrorMap (weightedPartialSum α ξ k ω))
                  (ξ k ω)
          + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 := by
  intro k hk
  have hAll :=
    sample_norm_le_noiseRadius_all_ae
      (B := B) (μ := μ) (ξ := ξ) (n := n) sample_norm_le_noiseRadius_ae
  filter_upwards [hAll] with ω hω
  exact weighted_smooth_step P B coeff_nonneg coeff_sum_le_one k hk ω hω

private theorem weighted_partialSum_sq_integrable
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {k : ℕ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (potential_integrable :
      Integrable (fun ω => B.potential (weightedPartialSum α ξ k ω)) μ)
    (partial_norm_le_noiseRadius_ae :
      ∀ᵐ ω ∂μ, ‖weightedPartialSum α ξ k ω‖ ≤ B.noiseRadius) :
    Integrable (fun ω => ‖weightedPartialSum α ξ k ω‖ ^ 2) μ := by
  have hScaled :
      Integrable (fun ω => (2 : ℝ) * B.potential (weightedPartialSum α ξ k ω)) μ := by
    simpa using potential_integrable.const_mul (2 : ℝ)
  have hMeas :
      AEStronglyMeasurable (fun ω => ‖weightedPartialSum α ξ k ω‖ ^ 2) μ := by
    have hNormMeas :
        Measurable (fun ω => ‖weightedPartialSum α ξ k ω‖) :=
      (weighted_partialSum_stronglyMeasurable_any sample_stronglyMeasurable k).norm.measurable
    exact (hNormMeas.pow_const 2).aestronglyMeasurable
  refine Integrable.mono' hScaled hMeas ?_
  filter_upwards [partial_norm_le_noiseRadius_ae] with ω hω
  have hSqLe :=
    B.norm_sq_le_two_potential_on_ball (weightedPartialSum α ξ k ω) hω
  have hLeftNonneg : 0 ≤ ‖weightedPartialSum α ξ k ω‖ ^ 2 := sq_nonneg _
  have hRightNonneg : 0 ≤ 2 * B.potential (weightedPartialSum α ξ k ω) := by
    nlinarith [hSqLe]
  simpa [Real.norm_of_nonneg hLeftNonneg, Real.norm_of_nonneg hRightNonneg] using hSqLe

private theorem weighted_linearized_cross_integrable
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {k : ℕ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (partial_sq_integrable :
      Integrable (fun ω => ‖weightedPartialSum α ξ k ω‖ ^ 2) μ)
    (sample_sq_integrable :
      Integrable (fun ω => ‖ξ k ω‖ ^ 2) μ)
    (partial_norm_le_noiseRadius_ae :
      ∀ᵐ ω ∂μ, ‖weightedPartialSum α ξ k ω‖ ≤ B.noiseRadius) :
    Integrable
      (fun ω =>
        P.toLinear
          (B.mirrorMap (weightedPartialSum α ξ k ω))
          (ξ k ω)) μ := by
  let Pflip : (VDual →L[ℝ] ℝ) →L[ℝ] VDual →L[ℝ] ℝ :=
    ContinuousLinearMap.flip (ContinuousLinearMap.apply ℝ ℝ)
  have hPartial :
      StronglyMeasurable (fun ω => weightedPartialSum α ξ k ω) :=
    weighted_partialSum_stronglyMeasurable_any sample_stronglyMeasurable k
  have hMirror :
      StronglyMeasurable
        (fun ω => B.mirrorMap (weightedPartialSum α ξ k ω)) :=
    B.mirrorMap_continuous.comp_stronglyMeasurable hPartial
  let coeffFun : Ω → VDual →L[ℝ] ℝ := fun ω =>
    P.toLinear (B.mirrorMap (weightedPartialSum α ξ k ω))
  have hCoeff :
      AEStronglyMeasurable coeffFun μ :=
    (P.toLinear.continuous.comp_stronglyMeasurable hMirror).aestronglyMeasurable
  have hXi : AEStronglyMeasurable (ξ k) μ :=
    (sample_stronglyMeasurable k).aestronglyMeasurable
  have hMeas :
      AEStronglyMeasurable (fun ω => coeffFun ω (ξ k ω)) μ := by
    simpa [Pflip, coeffFun] using Pflip.aestronglyMeasurable_comp₂ hCoeff hXi
  have hProd :
      Integrable
        (fun ω => ‖weightedPartialSum α ξ k ω‖ * ‖ξ k ω‖) μ :=
    integrable_norm_mul_of_sq_integrable
      hPartial (sample_stronglyMeasurable k) partial_sq_integrable sample_sq_integrable
  have hDom :
      Integrable
        (fun ω => B.D * (‖weightedPartialSum α ξ k ω‖ * ‖ξ k ω‖)) μ :=
    hProd.const_mul B.D
  refine Integrable.mono' hDom hMeas ?_
  filter_upwards [partial_norm_le_noiseRadius_ae] with ω hω
  have hMirrorBound :
      ‖B.mirrorMap (weightedPartialSum α ξ k ω)‖ ≤
        B.D * ‖weightedPartialSum α ξ k ω‖ :=
    B.mirrorMap_norm_le_of_mem_noiseRadius (weightedPartialSum α ξ k ω) hω
  calc
    ‖coeffFun ω (ξ k ω)‖
      ≤ ‖coeffFun ω‖ * ‖ξ k ω‖ := ContinuousLinearMap.le_opNorm _ _
    _ ≤ ‖B.mirrorMap (weightedPartialSum α ξ k ω)‖ * ‖ξ k ω‖ := by
          gcongr
          exact P.opNorm_le _
    _ ≤ (B.D * ‖weightedPartialSum α ξ k ω‖) * ‖ξ k ω‖ := by
          gcongr
    _ = B.D * (‖weightedPartialSum α ξ k ω‖ * ‖ξ k ω‖) := by ring

end

private theorem weighted_cross_term_zero_at
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n k : ℕ}
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (sample_integrable : ∀ k, k < n → Integrable (ξ k) μ)
    (sample_mean_zero : ∀ k, k < n → ∫ ω, ξ k ω ∂μ = 0)
    (future_condexp_zero :
      ∀ k, k + 1 < n →
        μ[ξ (k + 1) | naturalNoiseFiltration sample_stronglyMeasurable k] =ᵐ[μ] 0)
    (partial_sq_integrable :
      Integrable (fun ω => ‖weightedPartialSum α ξ k ω‖ ^ 2) μ)
    (sample_sq_integrable :
      Integrable (fun ω => ‖ξ k ω‖ ^ 2) μ)
    (partial_norm_le_noiseRadius_ae :
      ∀ᵐ ω ∂μ, ‖weightedPartialSum α ξ k ω‖ ≤ B.noiseRadius)
    (hk : k < n) :
    Integrable
        (fun ω =>
          α k
            * P.toLinear
                (B.mirrorMap (weightedPartialSum α ξ k ω))
                (ξ k ω)) μ ∧
      ∫ ω,
          α k
            * P.toLinear
                (B.mirrorMap (weightedPartialSum α ξ k ω))
                (ξ k ω) ∂μ = 0 := by
  cases k with
  | zero =>
      have hInt :
          Integrable
            (fun ω => P.toLinear (B.mirrorMap 0) (ξ 0 ω)) μ := by
        simpa [weightedPartialSum] using
          weighted_linearized_cross_integrable P B
            sample_stronglyMeasurable partial_sq_integrable sample_sq_integrable
            partial_norm_le_noiseRadius_ae
      refine ⟨hInt.const_mul (α 0), ?_⟩
      have hApply :
          ∫ ω, P.toLinear (B.mirrorMap 0) (ξ 0 ω) ∂μ =
            P.toLinear (B.mirrorMap 0) (∫ ω, ξ 0 ω ∂μ) :=
        (P.toLinear (B.mirrorMap 0)).integral_comp_comm (sample_integrable 0 hk)
      calc
        ∫ ω, α 0 * P.toLinear (B.mirrorMap 0) (ξ 0 ω) ∂μ
          = α 0 * ∫ ω, P.toLinear (B.mirrorMap 0) (ξ 0 ω) ∂μ := by
              rw [MeasureTheory.integral_const_mul]
        _ = α 0 * P.toLinear (B.mirrorMap 0) (∫ ω, ξ 0 ω ∂μ) := by
              rw [hApply]
        _ = 0 := by rw [sample_mean_zero 0 hk]; simp
  | succ k =>
      have hk' : k + 1 < n := hk
      have hInt :
          Integrable
            (fun ω =>
              P.toLinear
                (B.mirrorMap (weightedPartialSum α ξ (k + 1) ω))
                (ξ (k + 1) ω)) μ := by
        simpa using
          weighted_linearized_cross_integrable P B
            sample_stronglyMeasurable partial_sq_integrable sample_sq_integrable
            partial_norm_le_noiseRadius_ae
      have hZero :
          ∫ ω,
              P.toLinear
                (B.mirrorMap (weightedPartialSum α ξ (k + 1) ω))
                (ξ (k + 1) ω) ∂μ = 0 :=
        integral_clm_apply_eq_zero_of_condexp_zero
          (μ := μ)
          (m := naturalNoiseFiltration sample_stronglyMeasurable k)
          (show naturalNoiseFiltration sample_stronglyMeasurable k ≤
              inferInstanceAs (MeasurableSpace Ω) from Filtration.le _ _)
          (hL := weighted_crossTermCoefficient_aestronglyMeasurable P B sample_stronglyMeasurable k)
          (hLξ := hInt)
          (hξ := sample_integrable (k + 1) hk')
          (hCondZero := future_condexp_zero k hk')
      refine ⟨hInt.const_mul (α (k + 1)), ?_⟩
      calc
        ∫ ω,
            α (k + 1)
              * P.toLinear
                  (B.mirrorMap (weightedPartialSum α ξ (k + 1) ω))
                  (ξ (k + 1) ω) ∂μ
          = α (k + 1)
              * ∫ ω,
                  P.toLinear
                    (B.mirrorMap (weightedPartialSum α ξ (k + 1) ω))
                    (ξ (k + 1) ω) ∂μ := by
                    rw [MeasureTheory.integral_const_mul]
        _ = 0 := by simp [hZero]

private theorem weighted_partial_potential_sq_integrable_and_bound
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ} {sigma : ℝ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (sample_integrable : ∀ k, k < n → Integrable (ξ k) μ)
    (sample_mean_zero : ∀ k, k < n → ∫ ω, ξ k ω ∂μ = 0)
    (future_condexp_zero :
      ∀ k, k + 1 < n →
        μ[ξ (k + 1) | naturalNoiseFiltration sample_stronglyMeasurable k] =ᵐ[μ] 0)
    (sample_norm_le_noiseRadius_ae :
      ∀ k, k < n → ∀ᵐ ω ∂μ, ‖ξ k ω‖ ≤ B.noiseRadius)
    (second_moment_bound :
      ∀ k, k < n →
        Integrable (fun ω => ‖ξ k ω‖ ^ 2) μ ∧
          ∫ ω, ‖ξ k ω‖ ^ 2 ∂μ ≤ sigma ^ 2) :
    ∀ k, k ≤ n →
      Integrable (fun ω => B.potential (weightedPartialSum α ξ k ω)) μ ∧
      Integrable (fun ω => ‖weightedPartialSum α ξ k ω‖ ^ 2) μ ∧
      ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ ≤
        (B.D / 2) * sigma ^ 2 * Finset.sum (Finset.range k) (fun i => (α i) ^ 2) := by
  intro k hk
  induction' k with k ih
  · refine ⟨?_, ?_, ?_⟩
    · have hZeroReal : Integrable (fun _ : Ω => (0 : ℝ)) μ := by
        simp
      convert hZeroReal using 1
      ext ω
      simp [weightedPartialSum, B.potential_zero]
    · have hZeroReal : Integrable (fun _ : Ω => (0 : ℝ)) μ := by
        simp
      convert hZeroReal using 1
      ext ω
      simp [weightedPartialSum]
    · simp [weightedPartialSum, B.potential_zero]
  · have hk' : k < n := Nat.lt_of_succ_le hk
    rcases ih (Nat.le_of_lt hk') with ⟨hPrevPotInt, hPrevSqInt, hPrevBound⟩
    have hVarInt := (second_moment_bound k hk').1
    have hVarBound := (second_moment_bound k hk').2
    have hPrevBall :=
      weightedPartialSum_norm_le_noiseRadius_ae
        P B coeff_nonneg coeff_sum_le_one sample_norm_le_noiseRadius_ae k (Nat.le_of_lt hk')
    have hNextBall :=
      weightedPartialSum_norm_le_noiseRadius_ae
        P B coeff_nonneg coeff_sum_le_one sample_norm_le_noiseRadius_ae
        (k + 1) (Nat.succ_le_of_lt hk')
    have hCross :=
      weighted_cross_term_zero_at
        P B sample_stronglyMeasurable sample_integrable sample_mean_zero
        future_condexp_zero hPrevSqInt hVarInt hPrevBall hk'
    have hCrossInt := hCross.1
    have hCrossZero := hCross.2
    have hSmooth :
        ∀ᵐ ω ∂μ,
          B.potential (weightedPartialSum α ξ (k + 1) ω) ≤
            B.potential (weightedPartialSum α ξ k ω)
              + α k
              * P.toLinear
                  (B.mirrorMap (weightedPartialSum α ξ k ω))
                  (ξ k ω)
              + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 := by
      exact
        weighted_smooth_step_ae
          P B coeff_nonneg coeff_sum_le_one sample_norm_le_noiseRadius_ae k hk'
    have hScaleNonneg : 0 ≤ (B.D / 2) * (α k) ^ 2 := by
      have hDhalf : 0 ≤ B.D / 2 := by nlinarith [B.D_nonneg]
      exact mul_nonneg hDhalf (sq_nonneg _)
    let f : Ω → ℝ := fun ω => B.potential (weightedPartialSum α ξ k ω)
    let g : Ω → ℝ := fun ω =>
      α k * P.toLinear (B.mirrorMap (weightedPartialSum α ξ k ω)) (ξ k ω)
    let h : Ω → ℝ := fun ω => ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2
    have hf : Integrable f μ := by simpa [f] using hPrevPotInt
    have hg : Integrable g μ := by simpa [g] using hCrossInt
    have hh : Integrable h μ := by
      simpa [h] using hVarInt.const_mul ((B.D / 2) * (α k) ^ 2)
    have hAbsRhsInt :
        Integrable
          (fun ω =>
            B.potential (weightedPartialSum α ξ k ω)
              + ‖α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω)‖
              + ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2) μ := by
      simpa [f, g, h, add_assoc] using hf.add (hg.norm.add hh)
    have hNextMeas :
        AEStronglyMeasurable
          (fun ω => B.potential (weightedPartialSum α ξ (k + 1) ω)) μ := by
      exact B.potential_continuous.comp_aestronglyMeasurable
        ((weighted_partialSum_stronglyMeasurable_any sample_stronglyMeasurable (k + 1)).aestronglyMeasurable)
    have hNextPotInt :
        Integrable (fun ω => B.potential (weightedPartialSum α ξ (k + 1) ω)) μ := by
      refine Integrable.mono' hAbsRhsInt hNextMeas ?_
      filter_upwards [hSmooth, hPrevBall, hNextBall] with ω hω hPrevω hNextω
      have hPotNonnegNext :
          0 ≤ B.potential (weightedPartialSum α ξ (k + 1) ω) :=
        B.potential_nonneg_of_mem_noiseRadius (weightedPartialSum α ξ (k + 1) ω) hNextω
      have hPotNonneg :
          0 ≤ B.potential (weightedPartialSum α ξ k ω) :=
        B.potential_nonneg_of_mem_noiseRadius (weightedPartialSum α ξ k ω) hPrevω
      have hVarNonneg :
          0 ≤ ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 := by
        exact mul_nonneg hScaleNonneg (sq_nonneg _)
      have hDom :
          B.potential (weightedPartialSum α ξ (k + 1) ω) ≤
            B.potential (weightedPartialSum α ξ k ω)
              + ‖α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω)‖
              + ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 := by
        have hAbs : α k
            * P.toLinear (B.mirrorMap (weightedPartialSum α ξ k ω)) (ξ k ω)
            ≤ ‖α k
                * P.toLinear (B.mirrorMap (weightedPartialSum α ξ k ω)) (ξ k ω)‖ := by
          exact le_abs_self _
        linarith
      have hRhsNonneg :
          0 ≤
            B.potential (weightedPartialSum α ξ k ω)
              + ‖α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω)‖
              + ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 := by
        positivity
      simpa [Real.norm_of_nonneg hPotNonnegNext, Real.norm_of_nonneg hRhsNonneg] using hDom
    have hNextSqInt :
        Integrable (fun ω => ‖weightedPartialSum α ξ (k + 1) ω‖ ^ 2) μ :=
      weighted_partialSum_sq_integrable
        P B sample_stronglyMeasurable hNextPotInt hNextBall
    have hRhsInt :
        Integrable
          (fun ω =>
            B.potential (weightedPartialSum α ξ k ω)
              + α k
                  * P.toLinear
                      (B.mirrorMap (weightedPartialSum α ξ k ω))
                      (ξ k ω)
              + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2) μ := by
      simpa [f, g, h, add_assoc] using hf.add (hg.add hh)
    have hMono :
        ∫ ω, B.potential (weightedPartialSum α ξ (k + 1) ω) ∂μ ≤
          ∫ ω,
            B.potential (weightedPartialSum α ξ k ω)
              + α k
                  * P.toLinear
                      (B.mirrorMap (weightedPartialSum α ξ k ω))
                      (ξ k ω)
              + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 ∂μ := by
      exact integral_mono_ae hNextPotInt hRhsInt hSmooth
    have hSplitIntegral :
        ∫ ω,
            B.potential (weightedPartialSum α ξ k ω)
              + α k
                  * P.toLinear
                      (B.mirrorMap (weightedPartialSum α ξ k ω))
                      (ξ k ω)
              + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 ∂μ
          =
            ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ
              + ∫ ω,
                  α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω) ∂μ
              + ∫ ω, ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 ∂μ := by
      have hAdd1 :
          ∫ ω, (f + g + h) ω ∂μ =
            ∫ ω, (f + g) ω ∂μ + ∫ ω, h ω ∂μ := by
        simpa [Pi.add_apply] using
          (integral_add (hf.add hg) hh : ∫ ω, ((f + g) + h) ω ∂μ = _)
      have hAdd2 :
          ∫ ω, (f + g) ω ∂μ =
            ∫ ω, f ω ∂μ + ∫ ω, g ω ∂μ := by
        simpa [Pi.add_apply] using
          (integral_add hf hg : ∫ ω, (f + g) ω ∂μ = _)
      calc
        ∫ ω,
            B.potential (weightedPartialSum α ξ k ω)
              + α k
                  * P.toLinear
                      (B.mirrorMap (weightedPartialSum α ξ k ω))
                      (ξ k ω)
              + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 ∂μ
          = ∫ ω, (f + g + h) ω ∂μ := by simp [f, g, h, add_assoc]
        _ = ∫ ω, (f + g) ω ∂μ + ∫ ω, h ω ∂μ := hAdd1
        _ = (∫ ω, f ω ∂μ + ∫ ω, g ω ∂μ) + ∫ ω, h ω ∂μ := by rw [hAdd2]
        _ = ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ
              + ∫ ω,
                  α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω) ∂μ
              + ∫ ω, ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 ∂μ := by
                simp [f, g, h]
    have hVarIntegral :
        ∫ ω, ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 ∂μ =
          (B.D / 2) * (α k) ^ 2 * ∫ ω, ‖ξ k ω‖ ^ 2 ∂μ := by
      rw [integral_const_mul]
    have hNextBound :
        ∫ ω, B.potential (weightedPartialSum α ξ (k + 1) ω) ∂μ ≤
          (B.D / 2) * sigma ^ 2 * Finset.sum (Finset.range (k + 1)) (fun i => (α i) ^ 2) := by
      calc
        ∫ ω, B.potential (weightedPartialSum α ξ (k + 1) ω) ∂μ
          ≤ ∫ ω,
              B.potential (weightedPartialSum α ξ k ω)
                + α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω)
                + (B.D / 2) * (α k) ^ 2 * ‖ξ k ω‖ ^ 2 ∂μ := hMono
        _ = ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ
              + ∫ ω,
                  α k
                    * P.toLinear
                        (B.mirrorMap (weightedPartialSum α ξ k ω))
                        (ξ k ω) ∂μ
              + ∫ ω, ((B.D / 2) * (α k) ^ 2) * ‖ξ k ω‖ ^ 2 ∂μ := hSplitIntegral
        _ = ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ
              + 0
              + (B.D / 2) * (α k) ^ 2 * ∫ ω, ‖ξ k ω‖ ^ 2 ∂μ := by
                rw [hCrossZero, hVarIntegral]
        _ ≤ ∫ ω, B.potential (weightedPartialSum α ξ k ω) ∂μ
              + 0
              + (B.D / 2) * (α k) ^ 2 * sigma ^ 2 := by
                gcongr
        _ ≤ (B.D / 2) * sigma ^ 2 * Finset.sum (Finset.range k) (fun i => (α i) ^ 2)
              + 0
              + (B.D / 2) * (α k) ^ 2 * sigma ^ 2 := by
                gcongr
        _ = (B.D / 2) * sigma ^ 2 * Finset.sum (Finset.range (k + 1)) (fun i => (α i) ^ 2) := by
              rw [Finset.sum_range_succ]
              ring
    exact ⟨hNextPotInt, hNextSqInt, hNextBound⟩

private theorem weighted_noise_second_moment_bound
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ} {sigma : ℝ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (sample_integrable : ∀ k, k < n → Integrable (ξ k) μ)
    (sample_mean_zero : ∀ k, k < n → ∫ ω, ξ k ω ∂μ = 0)
    (future_condexp_zero :
      ∀ k, k + 1 < n →
        μ[ξ (k + 1) | naturalNoiseFiltration sample_stronglyMeasurable k] =ᵐ[μ] 0)
    (sample_norm_le_noiseRadius_ae :
      ∀ k, k < n → ∀ᵐ ω ∂μ, ‖ξ k ω‖ ≤ B.noiseRadius)
    (second_moment_bound :
      ∀ k, k < n →
        Integrable (fun ω => ‖ξ k ω‖ ^ 2) μ ∧
          ∫ ω, ‖ξ k ω‖ ^ 2 ∂μ ≤ sigma ^ 2) :
    ∫ ω, ‖weightedPartialSum α ξ n ω‖ ^ 2 ∂μ ≤
      B.D * sigma ^ 2 * Finset.sum (Finset.range n) (fun i => (α i) ^ 2) := by
  let hAll :=
    weighted_partial_potential_sq_integrable_and_bound
      P B coeff_nonneg coeff_sum_le_one sample_stronglyMeasurable sample_integrable
      sample_mean_zero future_condexp_zero sample_norm_le_noiseRadius_ae second_moment_bound
  have hFinal := hAll n le_rfl
  have hFinalPotInt := hFinal.1
  have hFinalBound := hFinal.2.2
  have hFinalBall :=
    weightedPartialSum_norm_le_noiseRadius_ae
      P B coeff_nonneg coeff_sum_le_one sample_norm_le_noiseRadius_ae n le_rfl
  have hScaled :
      Integrable (fun ω => 2 * B.potential (weightedPartialSum α ξ n ω)) μ := by
    simpa using hFinalPotInt.const_mul 2
  have hMono :
      ∫ ω, ‖weightedPartialSum α ξ n ω‖ ^ 2 ∂μ ≤
        ∫ ω, 2 * B.potential (weightedPartialSum α ξ n ω) ∂μ := by
    refine integral_mono_ae hFinal.2.1 hScaled ?_
    filter_upwards [hFinalBall] with ω hω
    exact B.norm_sq_le_two_potential_on_ball (weightedPartialSum α ξ n ω) hω
  calc
    ∫ ω, ‖weightedPartialSum α ξ n ω‖ ^ 2 ∂μ
      ≤ ∫ ω, 2 * B.potential (weightedPartialSum α ξ n ω) ∂μ := hMono
    _ = 2 * ∫ ω, B.potential (weightedPartialSum α ξ n ω) ∂μ := by
          rw [integral_const_mul]
    _ ≤ 2 * ((B.D / 2) * sigma ^ 2 * Finset.sum (Finset.range n) (fun i => (α i) ^ 2)) := by
          gcongr
    _ = B.D * sigma ^ 2 * Finset.sum (Finset.range n) (fun i => (α i) ^ 2) := by ring

/-- First-moment bound for a weighted sum of centered noises under Assumption 4. -/
theorem weighted_noise_first_moment_bound
    (P : ContinuousDualPairingContext VDual V)
    (B : Assumption4_LocalSmoothProxyPotential V VDual P)
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ξ : ℕ → Ω → VDual} {α : ℕ → ℝ} {n : ℕ} {sigma : ℝ}
    (coeff_nonneg : ∀ i < n, 0 ≤ α i)
    (coeff_sum_le_one : Finset.sum (Finset.range n) α ≤ 1)
    (sample_stronglyMeasurable : ∀ i, StronglyMeasurable (ξ i))
    (sample_integrable : ∀ k, k < n → Integrable (ξ k) μ)
    (sample_mean_zero : ∀ k, k < n → ∫ ω, ξ k ω ∂μ = 0)
    (future_condexp_zero :
      ∀ k, k + 1 < n →
        μ[ξ (k + 1) | naturalNoiseFiltration sample_stronglyMeasurable k] =ᵐ[μ] 0)
    (sample_norm_le_noiseRadius_ae :
      ∀ k, k < n → ∀ᵐ ω ∂μ, ‖ξ k ω‖ ≤ B.noiseRadius)
    (second_moment_bound :
      ∀ k, k < n →
        Integrable (fun ω => ‖ξ k ω‖ ^ 2) μ ∧
          ∫ ω, ‖ξ k ω‖ ^ 2 ∂μ ≤ sigma ^ 2) :
    ∫ ω, ‖weightedPartialSum α ξ n ω‖ ∂μ ≤
      Real.sqrt (B.D * sigma ^ 2 * Finset.sum (Finset.range n) (fun i => (α i) ^ 2)) := by
  let hAll :=
    weighted_partial_potential_sq_integrable_and_bound
      P B coeff_nonneg coeff_sum_le_one sample_stronglyMeasurable sample_integrable
      sample_mean_zero future_condexp_zero sample_norm_le_noiseRadius_ae second_moment_bound
  have hSqInt :
      Integrable (fun ω => ‖weightedPartialSum α ξ n ω‖ ^ 2) μ :=
    (hAll n le_rfl).2.1
  have hFirst :=
    integral_norm_le_sqrt_second_moment
      (μ := μ) (f := fun ω => weightedPartialSum α ξ n ω) hSqInt
  have hSecond :=
    weighted_noise_second_moment_bound P B coeff_nonneg coeff_sum_le_one
      sample_stronglyMeasurable sample_integrable
      sample_mean_zero future_condexp_zero sample_norm_le_noiseRadius_ae second_moment_bound
  calc
    ∫ ω, ‖weightedPartialSum α ξ n ω‖ ∂μ
      ≤ Real.sqrt (∫ ω, ‖weightedPartialSum α ξ n ω‖ ^ 2 ∂μ) := hFirst
    _ ≤ Real.sqrt (B.D * sigma ^ 2 * Finset.sum (Finset.range n) (fun i => (α i) ^ 2)) := by
          exact Real.sqrt_le_sqrt hSecond

end WeightedNoise

namespace StochasticSteepestDescentGeometryContext

variable {Ω V : Type*}
variable [MeasurableSpace Ω]
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [MeasurableSpace (StrongDual ℝ V)] [BorelSpace (StrongDual ℝ V)]
variable [SecondCountableTopology (StrongDual ℝ V)]
variable [CompleteSpace (StrongDual ℝ V)]

private def flatBatchIndex
    (S : StochasticSteepestDescentGeometryContext Ω V) (m : ℕ) : Fin S.batchSize :=
  ⟨m % S.batchSize, Nat.mod_lt _ S.batchSize_pos⟩

private theorem pairIndexed_iIndep
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    iIndepFun (fun p : ℕ × Fin S.batchSize => S.ξ p.1 p.2) S.μ := by
  simpa [StochasticSteepestDescentGeometryContext.batchNoise] using
    (ProbabilityTheory.iIndepFun_uncurry'
      (X := fun t i => S.ξ t i)
      (mX := fun t i => (S.sample_stronglyMeasurable t i).measurable)
      (h1 := S.freshBatch_iIndep)
      (h2 := S.withinBatch_iIndep))

private theorem fixedTime_iIndep
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) :
    iIndepFun
      (fun i =>
        if hi : i < S.batchSize then S.ξ t ⟨i, hi⟩ else fun _ => 0) S.μ := by
  let shifted : ℕ → Ω → StrongDual ℝ V := fun m =>
    S.ξ (t + m / S.batchSize) (S.flatBatchIndex m)
  have hShift :
      iIndepFun shifted S.μ := by
    let e : ℕ → ℕ × Fin S.batchSize := fun m =>
      (t + m / S.batchSize, S.flatBatchIndex m)
    have hInj : Function.Injective e := by
      intro a b h
      have hDiv : a / S.batchSize = b / S.batchSize := by
        exact Nat.add_left_cancel (congrArg Prod.fst h)
      have hMod : a % S.batchSize = b % S.batchSize := by
        exact Fin.ext_iff.mp (congrArg Prod.snd h)
      calc
        a = a % S.batchSize + S.batchSize * (a / S.batchSize) := by
              exact (Nat.mod_add_div a S.batchSize).symm
        _ = b % S.batchSize + S.batchSize * (b / S.batchSize) := by rw [hMod, hDiv]
        _ = b := by exact Nat.mod_add_div b S.batchSize
    simpa [shifted, e, flatBatchIndex] using (pairIndexed_iIndep S).precomp hInj
  have hComp :
      iIndepFun
        (fun i => (fun x : StrongDual ℝ V => if hi : i < S.batchSize then x else 0) ∘ shifted i)
        S.μ :=
    hShift.comp
      (fun i x => if hi : i < S.batchSize then x else 0)
      (by
        intro i
        by_cases hi : i < S.batchSize
        · simpa [hi] using (measurable_id : Measurable (fun x : StrongDual ℝ V => x))
        · simp [hi])
  have hEq :
      (fun i => (fun x : StrongDual ℝ V => if hi : i < S.batchSize then x else 0) ∘ shifted i) =
        (fun i =>
          if hi : i < S.batchSize then S.ξ t ⟨i, hi⟩ else fun _ => 0) := by
    funext i
    funext ω
    by_cases hi : i < S.batchSize
    · have hDiv : i / S.batchSize = 0 := Nat.div_eq_of_lt hi
      have hMod : i % S.batchSize = i := Nat.mod_eq_of_lt hi
      have hIndex : S.flatBatchIndex i = ⟨i, hi⟩ := by
        apply Fin.ext
        simp [flatBatchIndex, hMod]
      simp [shifted, hi, hDiv, hIndex]
    · simp [shifted, hi]
  exact hEq ▸ hComp

private def minibatchTruncatedSample
    (S : StochasticSteepestDescentGeometryContext Ω V) (t i : ℕ) :
    Ω → StrongDual ℝ V :=
  if hi : i < S.batchSize then S.ξ t ⟨i, hi⟩ else fun _ => 0

private lemma minibatchTruncatedSample_eq_of_lt
    (S : StochasticSteepestDescentGeometryContext Ω V) (t i : ℕ)
    (hi : i < S.batchSize) :
    S.minibatchTruncatedSample t i = S.ξ t ⟨i, hi⟩ := by
  simp [minibatchTruncatedSample, hi]

private lemma minibatchTruncatedSample_stronglyMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V) (t i : ℕ) :
    StronglyMeasurable (S.minibatchTruncatedSample t i) := by
  by_cases hi : i < S.batchSize
  · simpa [minibatchTruncatedSample, hi] using S.sample_stronglyMeasurable t ⟨i, hi⟩
  · simpa [minibatchTruncatedSample, hi] using
      (stronglyMeasurable_const : StronglyMeasurable (fun _ : Ω => (0 : StrongDual ℝ V)))

private lemma minibatchTruncatedSample_iIndep
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) :
    iIndepFun (S.minibatchTruncatedSample t) S.μ := by
  /-
  The concrete Lemma-5 bridge only needs the fixed-time fresh minibatch
  independence. We recover the zero-extended `ℕ`-indexed sequence locally from
  the within-batch and fresh-batch Assumption-1 fields above.
  -/
  simpa [minibatchTruncatedSample] using S.fixedTime_iIndep t

private def minibatchPartialSum
    (S : StochasticSteepestDescentGeometryContext Ω V) (t k : ℕ) (ω : Ω) :
    StrongDual ℝ V :=
  weightedPartialSum (fun _ => uniformBatchWeight S.batchSize) (S.minibatchTruncatedSample t) k ω

private theorem minibatchFutureCondexpZero
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) :
    ∀ k, k + 1 < S.batchSize →
      S.μ[S.minibatchTruncatedSample t (k + 1)
          | naturalNoiseFiltration (fun i => S.minibatchTruncatedSample_stronglyMeasurable t i) k]
        =ᵐ[S.μ] 0 := by
  /-
  The concrete Lemma-5 bridge uses three stronger Assumption-1 consequences:
  per-sample mean zero, fixed-time independence, and the derived
  future-noise conditional expectation zero statement proved here.
  -/
  intro k hk
  have hMeanZero :
      ∫ ω, S.minibatchTruncatedSample t (k + 1) ω ∂S.μ = 0 := by
    simpa [S.minibatchTruncatedSample_eq_of_lt t (k + 1) hk] using
      S.sample_mean_zero t ⟨k + 1, hk⟩
  exact centered_noise_condexp_natural_ae_eq_zero
    (μ := S.μ)
    (ξ := S.minibatchTruncatedSample t)
    (hξ := fun i => S.minibatchTruncatedSample_stronglyMeasurable t i)
    (hIndep := S.minibatchTruncatedSample_iIndep t)
    (Nat.lt_succ_self k)
    hMeanZero

/-- The concrete time-`t` minibatch noise process. -/
def minibatchNoiseProcess
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) (ω : Ω) :
    StrongDual ℝ V :=
  Finset.sum Finset.univ (fun i : Fin S.batchSize => uniformBatchWeight S.batchSize • S.ξ t i ω)

/-- The expected norm of the concrete minibatch noise process. -/
def expectedMinibatchNoise
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) : ℝ :=
  ∫ ω, ‖S.minibatchNoiseProcess t ω‖ ∂S.μ

private lemma minibatchNoiseProcess_eq_partialSum
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) :
    S.minibatchNoiseProcess t = S.minibatchPartialSum t S.batchSize := by
  funext ω
  unfold minibatchNoiseProcess minibatchPartialSum weightedPartialSum
  calc
    Finset.sum Finset.univ
        (fun i : Fin S.batchSize => uniformBatchWeight S.batchSize • S.ξ t i ω)
      = Finset.sum Finset.univ
          (fun i : Fin S.batchSize => uniformBatchWeight S.batchSize • S.minibatchTruncatedSample t i ω) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            simp [minibatchTruncatedSample, i.2]
    _ = Finset.sum (Finset.range S.batchSize)
          (fun i => uniformBatchWeight S.batchSize • S.minibatchTruncatedSample t i ω) := by
            simpa using
              (Fin.sum_univ_eq_sum_range (n := S.batchSize)
                (fun i => uniformBatchWeight S.batchSize • S.minibatchTruncatedSample t i ω))

/-- The sampled minibatch noise has zero mean under Assumption 1. -/
theorem minibatchNoise_eq_zero
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ) :
    S.minibatchNoise t = 0 := by
  calc
    S.minibatchNoise t = ∫ ω, S.minibatchNoiseProcess t ω ∂S.μ := by
      rfl
    _ = ∫ ω, S.minibatchPartialSum t S.batchSize ω ∂S.μ := by
          simp [S.minibatchNoiseProcess_eq_partialSum]
    _ = 0 := weightedPartialSum_mean_zero
          (sample_integrable := by
            intro i hi
            simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using S.sample_integrable t ⟨i, hi⟩)
          (sample_mean_zero := by
            intro i hi
            simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using S.sample_mean_zero t ⟨i, hi⟩)

theorem expectedMinibatchNoise_bound
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t,
      S.expectedMinibatchNoise t ≤ Real.sqrt S.D * S.sigma / Real.sqrt S.batchSizeℝ := by
  intro t
  letI : IsProbabilityMeasure S.μ := S.prob
  have hFirst :=
    weighted_noise_first_moment_bound
      S.pairing
      S.assumption4_localProxyPotential
      (μ := S.μ)
      (sigma := S.sigma)
      (ξ := S.minibatchTruncatedSample t)
      (α := fun _ => uniformBatchWeight S.batchSize)
      (n := S.batchSize)
      (coeff_nonneg := by intro i hi; exact uniformBatchWeight_nonneg)
      (coeff_sum_le_one := by
        simpa [StochasticSteepestDescentParameters.batchSizeℝ] using
          uniformBatchWeight_sum_le_one S.batchSize_pos)
      (sample_stronglyMeasurable := fun i => S.minibatchTruncatedSample_stronglyMeasurable t i)
      (sample_integrable := by
        intro i hi
        simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using S.sample_integrable t ⟨i, hi⟩)
      (sample_mean_zero := by
        intro i hi
        simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using S.sample_mean_zero t ⟨i, hi⟩)
      (future_condexp_zero := S.minibatchFutureCondexpZero t)
      (sample_norm_le_noiseRadius_ae := by
        intro i hi
        simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using
          S.sample_norm_le_noiseRadius_ae t ⟨i, hi⟩)
      (second_moment_bound := by
        intro i hi
        simpa [S.minibatchTruncatedSample_eq_of_lt t i hi] using S.second_moment_bound t ⟨i, hi⟩)
  have hCoeffSq :
      Finset.sum (Finset.range S.batchSize)
        (fun _ => (uniformBatchWeight S.batchSize) ^ 2) = 1 / S.batchSizeℝ := by
    simpa [StochasticSteepestDescentParameters.batchSizeℝ] using
      uniformBatchWeight_sq_sum_eq S.batchSize_pos
  have hDSigmaNonneg : 0 ≤ S.D * S.sigma ^ 2 := by
    exact mul_nonneg S.D_nonneg (sq_nonneg _)
  calc
    S.expectedMinibatchNoise t
      = ∫ ω, ‖S.minibatchPartialSum t S.batchSize ω‖ ∂S.μ := by
          simp [expectedMinibatchNoise, S.minibatchNoiseProcess_eq_partialSum]
    _ ≤
      Real.sqrt
        (S.D * S.sigma ^ 2
          * Finset.sum (Finset.range S.batchSize)
              (fun _ => (uniformBatchWeight S.batchSize) ^ 2)) := hFirst
    _ = Real.sqrt (S.D * S.sigma ^ 2 / S.batchSizeℝ) := by
          rw [hCoeffSq]
          ring_nf
    _ = Real.sqrt (S.D * S.sigma ^ 2) / Real.sqrt S.batchSizeℝ := by
          rw [Real.sqrt_div hDSigmaNonneg]
    _ = Real.sqrt S.D * S.sigma / Real.sqrt S.batchSizeℝ := by
          rw [Real.sqrt_mul S.D_nonneg, Real.sqrt_sq S.sigma_nonneg]

theorem minibatchNoiseNorm_le_expectedMinibatchNoise
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, S.minibatchNoiseNorm t ≤ S.expectedMinibatchNoise t := by
  intro t
  rw [StochasticSteepestDescentGeometryContext.minibatchNoiseNorm,
    StochasticSteepestDescentGeometryContext.minibatchNoise,
    StochasticSteepestDescentGeometryContext.expectedMinibatchNoise]
  exact MeasureTheory.norm_integral_le_integral_norm _

end StochasticSteepestDescentGeometryContext

end

end MlOptBoundsFormalization
