import Mathlib
import SteepestDescentOptimizationBounds.Assumptions
import SteepestDescentOptimizationBounds.WeightAndUpdateBounds

namespace SteepestDescentOptimizationBounds

open MeasureTheory
open ProbabilityTheory

noncomputable section

section IntegrabilityHelpers

/-- Square-integrability on a probability space implies integrability of the norm. -/
theorem integrable_norm_of_sq_integrable
    {Ω E : Type*}
    [MeasurableSpace Ω]
    [NormedAddCommGroup E]
    [MeasurableSpace E]
    {μ : Measure Ω} [IsProbabilityMeasure μ] {f : Ω → E}
    (hf : StronglyMeasurable f)
    (hf_sq : Integrable (fun ω => ‖f ω‖ ^ 2) μ) :
    Integrable (fun ω => ‖f ω‖) μ := by
  have hConst : Integrable (fun _ : Ω => (1 : ℝ)) μ := integrable_const 1
  refine Integrable.mono' ((hf_sq.add hConst).const_mul (1 / 2 : ℝ))
    hf.norm.aestronglyMeasurable ?_
  filter_upwards with ω
  have hYoung : ‖f ω‖ ≤ (‖f ω‖ ^ 2 + 1) / 2 := by
    nlinarith [sq_nonneg (‖f ω‖ - 1)]
  have hRightNonneg : 0 ≤ (‖f ω‖ ^ 2 + 1) / 2 := by positivity
  simpa [div_eq_mul_inv, mul_comm, Real.norm_of_nonneg (norm_nonneg _),
    Real.norm_of_nonneg hRightNonneg] using hYoung

/-- Square-integrability on a probability space implies vector-valued integrability. -/
theorem integrable_of_sq_integrable
    {Ω E : Type*}
    [MeasurableSpace Ω]
    [NormedAddCommGroup E]
    [MeasurableSpace E]
    {μ : Measure Ω} [IsProbabilityMeasure μ] {f : Ω → E}
    (hf : StronglyMeasurable f)
    (hf_sq : Integrable (fun ω => ‖f ω‖ ^ 2) μ) :
    Integrable f μ := by
  exact
    (integrable_norm_iff hf.aestronglyMeasurable).mp
      (integrable_norm_of_sq_integrable hf hf_sq)

end IntegrabilityHelpers

/--
Evaluating the flattened sample process at the lexicographic index of `(t, i)`
recovers the original sample `sample t i`.
-/
lemma flatSample_at_flatSampleIndex
    {Ω β : Type*}
    {batchSize : ℕ}
    (hb : 0 < batchSize)
    (sample : ℕ → Fin batchSize → Ω → β)
    (t : ℕ)
    (i : Fin batchSize) :
    flatSample hb sample (flatSampleIndex t i) = sample t i := by
  funext ω
  have hDiv : flatSampleIndex t i / batchSize = t := by
    unfold flatSampleIndex
    rw [Nat.mul_comm, Nat.add_comm, Nat.add_mul_div_left _ _ hb]
    simp [Nat.div_eq_of_lt i.2]
  have hMod : flatSampleIndex t i % batchSize = i.1 := by
    unfold flatSampleIndex
    rw [Nat.mul_comm, Nat.add_comm, Nat.add_mul_mod_self_left]
    exact Nat.mod_eq_of_lt i.2
  simp [flatSample, hDiv, hMod]

private lemma flatSample_measurable
    {Ω β : Type*}
    [MeasurableSpace Ω]
    [MeasurableSpace β]
    {batchSize : ℕ}
    (hb : 0 < batchSize)
    (sample : ℕ → Fin batchSize → Ω → β)
    (sample_measurable : ∀ t i, Measurable (sample t i))
    (j : ℕ) :
    Measurable (flatSample hb sample j) := by
  simpa [flatSample] using
    sample_measurable (j / batchSize) ⟨j % batchSize, Nat.mod_lt _ hb⟩

private lemma samplePrefixSigma_le_of_measurable
    {Ω β V : Type*}
    [MeasurableSpace Ω]
    [MeasurableSpace V]
    [MeasurableSpace β]
    {batchSize : ℕ}
    (hb : 0 < batchSize)
    (W : ℕ → Ω → V)
    (sample : ℕ → Fin batchSize → Ω → β)
    (hSample : ∀ t i, @Measurable Ω β inferInstance inferInstance (sample t i))
    (t : ℕ)
    (hW : @Measurable Ω V inferInstance inferInstance (W t))
    (i : Fin batchSize) :
    samplePrefixSigma hb W sample t i ≤ inferInstanceAs (MeasurableSpace Ω) := by
  let tuple := flatSamplePrefixTuple hb sample t i
  have hTupleMeasurable : Measurable tuple := by
    exact measurable_pi_lambda tuple <| fun j =>
      flatSample_measurable hb sample hSample j
  exact sup_le hW.comap_le hTupleMeasurable.comap_le

/--
Every previously revealed flattened sample is measurable with respect to the
prefix sigma-algebra generated by `W_t` and that flattened sample table.
-/
lemma flatSample_measurable_of_lt
    {Ω β V : Type*}
    [MeasurableSpace Ω]
    [MeasurableSpace V]
    [MeasurableSpace β]
    {batchSize : ℕ}
    (hb : 0 < batchSize)
    (W : ℕ → Ω → V)
    (sample : ℕ → Fin batchSize → Ω → β)
    {t : ℕ} {i : Fin batchSize} {j : ℕ}
    (hj : j < flatSampleIndex t i) :
    Measurable[samplePrefixSigma hb W sample t i] (flatSample hb sample j) := by
  let tuple := flatSamplePrefixTuple hb sample t i
  have hTuple :
      Measurable[samplePrefixSigma hb W sample t i] tuple := by
    refine Measurable.of_comap_le ?_
    change
      MeasurableSpace.comap tuple
          (inferInstance : MeasurableSpace (Fin (flatSampleIndex t i) → β)) ≤
        MeasurableSpace.comap (W t) (inferInstance : MeasurableSpace V) ⊔
          MeasurableSpace.comap tuple
            (inferInstance : MeasurableSpace (Fin (flatSampleIndex t i) → β))
    exact le_sup_right
  let proj : (Fin (flatSampleIndex t i) → β) → β := fun z => z ⟨j, hj⟩
  have hProj : Measurable proj := measurable_pi_apply _
  simpa [flatSample, flatSamplePrefixTuple, tuple, proj] using hProj.comp hTuple

namespace Assumption4_LocalSmoothProxyPotential

variable {V VDual : Type*}
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [NormedAddCommGroup VDual] [NormedSpace ℝ VDual]
variable {pairing : ContinuousDualPairingContext VDual V}

/-- The proxy potential is continuous because it has a Fréchet derivative everywhere. -/
lemma potential_continuous
    (P : Assumption4_LocalSmoothProxyPotential V VDual pairing) :
    Continuous P.potential := by
  refine continuous_iff_continuousAt.mpr ?_
  intro x
  exact (P.potential_fderiv_eq x).continuousAt

/-- Assumption 4 gives a Lipschitz mirror map on the closed noise ball. -/
lemma mirrorMap_lipschitzOn_noiseBall
    (P : Assumption4_LocalSmoothProxyPotential V VDual pairing) :
    LipschitzOnWith (Real.toNNReal P.D) P.mirrorMap
      (Metric.closedBall 0 P.noiseRadius) := by
  refine LipschitzOnWith.of_dist_le_mul ?_
  intro x hx y hy
  have hx' : ‖x‖ ≤ P.noiseRadius := by
    simpa [Metric.mem_closedBall, dist_eq_norm] using hx
  have hy' : ‖y‖ ≤ P.noiseRadius := by
    simpa [Metric.mem_closedBall, dist_eq_norm] using hy
  have hBound := P.mirrorMap_local_lipschitz.bound hx' hy'
  simpa [dist_eq_norm, norm_sub_rev, Real.toNNReal_of_nonneg P.D_nonneg] using hBound

/-- The mirror map is continuous on the closed Assumption-4 noise ball. -/
lemma mirrorMap_continuousOn_noiseBall
    (P : Assumption4_LocalSmoothProxyPotential V VDual pairing) :
    ContinuousOn P.mirrorMap (Metric.closedBall 0 P.noiseRadius) :=
  P.mirrorMap_lipschitzOn_noiseBall.continuousOn

/-- The mirror map becomes measurable after restricting its domain to the noise ball. -/
lemma mirrorMap_restrict_measurable
    (P : Assumption4_LocalSmoothProxyPotential V VDual pairing)
    [MeasurableSpace V] [BorelSpace V] [SecondCountableTopology V]
    [MeasurableSpace VDual] [BorelSpace VDual] [SecondCountableTopology VDual] :
    Measurable ((Metric.closedBall (0 : VDual) P.noiseRadius).restrict P.mirrorMap) := by
  exact
    (continuousOn_iff_continuous_restrict.1
      P.mirrorMap_continuousOn_noiseBall).measurable

/-- If a dual-valued process stays in the noise ball almost surely, then applying the
Assumption-4 mirror map preserves a.e. strong measurability. -/
lemma mirrorMap_comp_aestronglyMeasurable_of_mem_noiseBall_ae
    {Ω : Type*} [MeasurableSpace Ω]
    (P : Assumption4_LocalSmoothProxyPotential V VDual pairing)
    [MeasurableSpace V] [BorelSpace V] [SecondCountableTopology V]
    [MeasurableSpace VDual] [BorelSpace VDual] [SecondCountableTopology VDual]
    {m m0 : MeasurableSpace Ω} {μ : @Measure Ω m0} {f : Ω → VDual}
    (hf : AEStronglyMeasurable[m] f μ)
    (hball : ∀ᵐ ω ∂μ, ‖f ω‖ ≤ P.noiseRadius) :
    AEStronglyMeasurable[m] (fun ω => P.mirrorMap (f ω)) μ := by
  have hff' : f =ᵐ[μ] hf.mk f := hf.ae_eq_mk
  have hball' : ∀ᵐ ω ∂μ, ‖hf.mk f ω‖ ≤ P.noiseRadius := by
    filter_upwards [hball, hff'] with ω hω hEq
    simpa [hEq] using hω
  have hnorm_meas : Measurable[m] (fun ω => ‖hf.mk f ω‖) := by
    exact (hf.stronglyMeasurable_mk.norm).measurable
  have hs_meas : MeasurableSet[m] {ω | ‖hf.mk f ω‖ ≤ P.noiseRadius} := by
    change MeasurableSet[m] ((fun ω => ‖hf.mk f ω‖) ⁻¹' Set.Iic P.noiseRadius)
    exact hnorm_meas measurableSet_Iic
  let g : Ω → VDual := fun ω => if ‖hf.mk f ω‖ ≤ P.noiseRadius then hf.mk f ω else 0
  have hg_meas : Measurable[m] g := by
    simpa [g, Set.piecewise] using hf.measurable_mk.piecewise hs_meas measurable_const
  have hg_mem : ∀ ω, g ω ∈ Metric.closedBall (0 : VDual) P.noiseRadius := by
    intro ω
    by_cases hω : ‖hf.mk f ω‖ ≤ P.noiseRadius
    · simp [g, hω, Metric.mem_closedBall, dist_eq_norm]
    · have hzero : ‖(0 : VDual)‖ ≤ P.noiseRadius := by simpa using P.noiseRadius_nonneg
      simpa [g, hω, Metric.mem_closedBall] using hzero
  have hfg : hf.mk f =ᵐ[μ] g := by
    filter_upwards [hball'] with ω hω
    simp [g, hω]
  have hcod :
      Measurable[m]
        ((Metric.closedBall (0 : VDual) P.noiseRadius).codRestrict g
          (by intro ω; exact hg_mem ω)) := by
    exact Measurable.subtype_mk hg_meas
  have hMirrorMeas :
      Measurable[m] (fun ω => P.mirrorMap (g ω)) := by
    simpa [Function.comp_def, Set.restrict_comp_codRestrict
      (by intro ω; exact hg_mem ω)] using
      P.mirrorMap_restrict_measurable.comp hcod
  exact (hMirrorMeas.stronglyMeasurable.aestronglyMeasurable).congr <| by
    filter_upwards [hff', hfg] with ω hω1 hω2
    simp [hω1, hω2]

end Assumption4_LocalSmoothProxyPotential

/-!
Stochastic process support layer for the realized stochastic steepest-descent model.

Upstream dependencies:

- `Assumptions.lean` provides the stochastic geometry context, the primitive
  stochastic processes, and Assumptions 1--4.

Downstream use:

- `MinibatchNoise.lean` reuses the conditional-expectation and second-moment
  lemmas for the minibatch-noise process.
- `MomentumBounds.lean` reuses the measurability, integrability, and adaptedness
  lemmas for the momentum recursion.
- downstream expected-bound files use the iterate measurability and gradient
  integrability results.
-/

namespace StochasticSteepestDescentGeometryContext

variable {Ω V : Type*}
variable [MeasurableSpace Ω]
variable [NormedAddCommGroup V] [NormedSpace ℝ V]
variable [MeasurableSpace V] [BorelSpace V] [SecondCountableTopology V]
variable [MeasurableSpace (StrongDual ℝ V)] [BorelSpace (StrongDual ℝ V)]
variable [SecondCountableTopology (StrongDual ℝ V)] [CompleteSpace (StrongDual ℝ V)]

section PrivateLemmas

/-- Restricting the codomain to a measurable set lets us compose a
`Measurable` map into that set with a measurable restricted target map. -/
private lemma measurable_comp_of_measurable_restrict
    {α β γ : Type*}
    [MeasurableSpace α] [MeasurableSpace β] [MeasurableSpace γ]
    {s : Set β} {f : α → β} {g : β → γ}
    (hf : Measurable f) (hfs : ∀ x, f x ∈ s)
    (hg : Measurable (s.restrict g)) :
    Measurable (fun x => g (f x)) := by
  have hcod : Measurable (s.codRestrict f hfs) := hf.subtype_mk
  simpa [Function.comp_def, Set.restrict_comp_codRestrict hfs] using hg.comp hcod

/-- Assumption 3 gives a Lipschitz gradient map on the primal feasibility ball. -/
private lemma fGrad_lipschitzOn_constraintBall
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    LipschitzOnWith (Real.toNNReal S.L) S.fGrad S.constraintBall := by
  refine LipschitzOnWith.of_dist_le_mul ?_
  intro x hx y hy
  have hx' : ‖x‖ ≤ 1 / S.lambda := by
    simpa [StochasticSteepestDescentGeometryContext.constraintBall, Metric.mem_closedBall, dist_eq_norm] using hx
  have hy' : ‖y‖ ≤ 1 / S.lambda := by
    simpa [StochasticSteepestDescentGeometryContext.constraintBall, Metric.mem_closedBall, dist_eq_norm] using hy
  have hBound := S.assumption3_fLocalSmoothness.bound hx' hy'
  simpa [dist_eq_norm, norm_sub_rev, Real.toNNReal_of_nonneg S.L_pos.le] using hBound

/-- The gradient map restricted to the primal feasibility ball is measurable. -/
private lemma fGrad_restrict_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    Measurable (S.constraintBall.restrict S.fGrad) := by
  exact
    (continuousOn_iff_continuous_restrict.1
      (S.fGrad_lipschitzOn_constraintBall.continuousOn)).measurable

/-- Every realized iterate stays inside the Assumption-3 primal ball. -/
private lemma W_mem_constraintBall
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t ω, S.W t ω ∈ S.constraintBall := by
  intro t ω
  simpa [StochasticSteepestDescentGeometryContext.constraintBall, Metric.mem_closedBall, dist_eq_norm] using
    S.weight_bound_from_feasible_step t ω

/-- Internal measurability proof for the realized minibatch gradient. -/
private lemma minibatchGradient_measurable_internal
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.minibatchGradient t) := by
  intro t
  have hEq :
      S.minibatchGradient t =
        fun ω =>
          Finset.sum Finset.univ
            (fun i : Fin S.batchSize =>
              uniformBatchWeight S.batchSize • S.stochasticGradientSample t i ω) := by
    funext ω
    exact S.minibatchGradient_spec t ω
  rw [hEq]
  exact Finset.measurable_fun_sum Finset.univ fun i _ =>
    (S.assumption1_sampling.sample_measurable t i).const_smul
      (uniformBatchWeight S.batchSize)

/-- Internal measurability proof for the initialized momentum process. -/
private lemma momentum_zero_measurable_internal
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    Measurable (S.momentum 0) := by
  rcases S.momentum_zero_eq_zero_or_minibatchGradient with hZero | hBatch
  · have hEq : S.momentum 0 = fun _ : Ω => (0 : StrongDual ℝ V) := by
      funext ω
      simp [hZero ω]
    rw [hEq]
    exact measurable_const
  · have hEq : S.momentum 0 = S.minibatchGradient 0 := by
      funext ω
      exact hBatch ω
    rw [hEq]
    exact S.minibatchGradient_measurable_internal 0

/-- Internal measurability proof for the momentum recursion. -/
private lemma momentum_measurable_internal
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.momentum t) := by
  intro t
  induction t with
  | zero =>
      simpa using S.momentum_zero_measurable_internal
  | succ t ih =>
      have hEq :
          S.momentum (t + 1) =
            fun ω =>
              S.beta • S.momentum t ω + (1 - S.beta) • S.minibatchGradient (t + 1) ω := by
        funext ω
        simpa using S.momentum_succ t ω
      rw [hEq]
      exact (ih.const_smul S.beta).add
        ((S.minibatchGradient_measurable_internal (t + 1)).const_smul (1 - S.beta))

private theorem flatSampleIndex_lt_of_lt_time
    (S : StochasticSteepestDescentGeometryContext Ω V)
    {s t : ℕ} (hst : s < t) (j : Fin S.batchSize) (i : Fin S.batchSize) :
    flatSampleIndex s j < flatSampleIndex t i := by
  calc
    flatSampleIndex s j = s * S.batchSize + j.1 := rfl
    _ < s * S.batchSize + S.batchSize := by
          exact Nat.add_lt_add_left j.2 _
    _ = (s + 1) * S.batchSize := by rw [Nat.succ_mul]
    _ ≤ t * S.batchSize := by
          exact Nat.mul_le_mul_right S.batchSize (Nat.succ_le_of_lt hst)
    _ ≤ t * S.batchSize + i.1 := Nat.le_add_right _ _
    _ = flatSampleIndex t i := rfl

private theorem sample_prefixMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) {s : ℕ}
    (hs : s < t) (j : Fin S.batchSize) :
    Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.stochasticGradientSample s j) := by
  have hlt : flatSampleIndex s j < flatSampleIndex t i :=
    S.flatSampleIndex_lt_of_lt_time hs j i
  have hFlat :
      Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        (flatSample S.batchSize_pos S.stochasticGradientSample (flatSampleIndex s j)) := by
    exact flatSample_measurable_of_lt
      S.batchSize_pos S.W S.stochasticGradientSample (t := t) (i := i) hlt
  simpa [flatSample_at_flatSampleIndex S.batchSize_pos S.stochasticGradientSample s j] using hFlat

private theorem minibatchGradient_prefixStronglyMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) {s : ℕ}
    (hs : s < t) :
    StronglyMeasurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.minibatchGradient s) := by
  have hEq :
      S.minibatchGradient s =
        fun ω =>
          Finset.sum Finset.univ
            (fun j : Fin S.batchSize =>
              uniformBatchWeight S.batchSize • S.stochasticGradientSample s j ω) := by
    funext ω
    exact S.minibatchGradient_spec s ω
  rw [hEq]
  have hMeas :
      Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        (fun ω =>
          Finset.sum Finset.univ
            (fun j : Fin S.batchSize =>
              uniformBatchWeight S.batchSize • S.stochasticGradientSample s j ω)) := by
    exact Finset.measurable_fun_sum Finset.univ fun j _ =>
      (S.sample_prefixMeasurable_before t i hs j).const_smul
        (uniformBatchWeight S.batchSize)
  exact hMeas.stronglyMeasurable

private theorem momentum_prefixStronglyMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s < t) :
    StronglyMeasurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.momentum s) := by
  revert hs
  induction s with
  | zero =>
      intro hs
      rcases S.momentum_zero_eq_zero_or_minibatchGradient with hZero | hBatch
      · have hEq : S.momentum 0 = fun _ : Ω => (0 : StrongDual ℝ V) := by
          funext ω
          simp [hZero ω]
        rw [hEq]
        exact stronglyMeasurable_const
      · have hEq : S.momentum 0 = S.minibatchGradient 0 := by
          funext ω
          exact hBatch ω
        rw [hEq]
        exact S.minibatchGradient_prefixStronglyMeasurable_before t i hs
  | succ s ih =>
      intro hs
      have hs' : s < t := Nat.lt_trans (Nat.lt_succ_self s) hs
      have hEq :
          S.momentum (s + 1) =
            fun ω =>
              S.beta • S.momentum s ω + (1 - S.beta) • S.minibatchGradient (s + 1) ω := by
        funext ω
        simpa using S.momentum_succ s ω
      rw [hEq]
      exact (ih hs').const_smul S.beta |>.add
        ((S.minibatchGradient_prefixStronglyMeasurable_before t i hs).const_smul
          (1 - S.beta))

private theorem C_prefixStronglyMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s < t) :
    StronglyMeasurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.C s) := by
  simpa [StochasticSteepestDescentGeometryContext.C] using
    ((S.momentum_prefixStronglyMeasurable_before t i s hs).const_smul S.beta).add
      ((S.minibatchGradient_prefixStronglyMeasurable_before t i hs).const_smul (1 - S.beta))

private theorem aStar_prefixStronglyMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s < t) :
    StronglyMeasurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.aStar s) := by
  have hMeas :
      Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        (S.aStar s) := by
    simpa [StochasticSteepestDescentGeometryContext.aStar] using
      S.lmo_measurable.comp (S.C_prefixStronglyMeasurable_before t i s hs).measurable
  exact hMeas.stronglyMeasurable

private theorem W_prefixMeasurable_before
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s < t) :
    Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.W s) := by
  revert hs
  induction s with
  | zero =>
      intro hs
      have hEq : S.W 0 = fun _ : Ω => S.W0 := by
        funext ω
        simpa using S.W_zero ω
      rw [hEq]
      exact measurable_const
  | succ s ih =>
      intro hs
      have hs' : s < t := Nat.lt_trans (Nat.lt_succ_self s) hs
      have hEq :
          S.W (s + 1) =
            fun ω => ((1 - S.lambda * S.eta) • S.W s ω) + S.eta • S.aStar s ω := by
        funext ω
        simpa [StochasticSteepestDescentGeometryContext.aStar,
          StochasticSteepestDescentGeometryContext.C] using S.update_eq s ω
      rw [hEq]
      exact (ih hs').const_smul (1 - S.lambda * S.eta) |>.add
        ((S.aStar_prefixStronglyMeasurable_before t i s hs').measurable.const_smul S.eta)

end PrivateLemmas

section PublicTheorems

/-- The realized minibatch gradient is measurable at each time. -/
lemma minibatchGradient_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.minibatchGradient t) := by
  exact S.minibatchGradient_measurable_internal

/-- The Nesterov search direction is measurable at each time. -/
lemma C_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.C t) := by
  intro t
  simpa [StochasticSteepestDescentGeometryContext.C] using
    ((S.momentum_measurable_internal t).const_smul S.beta).add
      ((S.minibatchGradient_measurable t).const_smul (1 - S.beta))

/-- The realized linear minimization oracle is measurable at each time. -/
private lemma aStar_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.aStar t) := by
  intro t
  simpa [StochasticSteepestDescentGeometryContext.aStar] using
    S.lmo_measurable.comp (S.C_measurable t)

/-- The iterate process is measurable at each time. -/
lemma W_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.W t) := by
  intro t
  induction t with
  | zero =>
      have hEq : S.W 0 = fun _ : Ω => S.W0 := by
        funext ω
        simpa using S.W_zero ω
      rw [hEq]
      exact measurable_const
  | succ t ih =>
      have hEq :
          S.W (t + 1) =
            fun ω => ((1 - S.lambda * S.eta) • S.W t ω) + S.eta • S.aStar t ω := by
        funext ω
        simpa [StochasticSteepestDescentGeometryContext.aStar,
          StochasticSteepestDescentGeometryContext.C] using S.update_eq t ω
      rw [hEq]
      exact (ih.const_smul (1 - S.lambda * S.eta)).add
        ((S.aStar_measurable t).const_smul S.eta)

/-- The true gradient process is measurable at each time. -/
lemma grad_measurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Measurable (S.grad t) := by
  intro t
  exact measurable_comp_of_measurable_restrict
    (f := S.W t) (g := S.fGrad) (s := S.constraintBall)
    (S.W_measurable t) (S.W_mem_constraintBall t) S.fGrad_restrict_measurable

/-- The true gradient process is strongly measurable at each time. -/
lemma grad_stronglyMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, StronglyMeasurable (S.grad t) := by
  intro t
  exact (S.grad_measurable t).stronglyMeasurable

/-- The Assumption-4 radius bound makes the squared per-sample noise integrable. -/
private lemma ξ_sq_integrable
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) :
    Integrable (fun ω => ‖S.ξ t i ω‖ ^ 2) S.μ := by
  letI := S.prob
  have hξStrong : StronglyMeasurable (S.ξ t i) := by
    simpa [StochasticSteepestDescentGeometryContext.ξ] using
      (S.grad_stronglyMeasurable t).sub
        ((S.assumption1_sampling.sample_measurable t i).stronglyMeasurable)
  have hSqAEStrong :
      AEStronglyMeasurable (fun ω => ‖S.ξ t i ω‖ ^ 2) S.μ := by
    exact (hξStrong.norm.measurable.pow_const 2).aestronglyMeasurable
  have hConst : Integrable (fun _ : Ω => S.noiseRadius ^ 2) S.μ :=
    MeasureTheory.integrable_const _
  refine Integrable.mono' hConst hSqAEStrong ?_
  filter_upwards [S.assumption4_oracleSampleNoiseBound t i] with ω hω
  have hω' : ‖S.ξ t i ω‖ ≤ S.noiseRadius := by
    simpa [StochasticSteepestDescentGeometryContext.ξ,
      StochasticSteepestDescentGeometryContext.grad,
      StochasticSteepestDescentGeometryContext.noiseRadius] using hω
  have hSq : ‖S.ξ t i ω‖ ^ 2 ≤ S.noiseRadius ^ 2 := by
    nlinarith [hω', S.noiseRadius_nonneg, norm_nonneg (S.ξ t i ω)]
  simpa [Real.norm_of_nonneg (sq_nonneg _),
    Real.norm_of_nonneg (sq_nonneg _)] using hSq

/-- The refined per-sample noise is integrable by the Assumption-4 radius bound. -/
private lemma ξ_integrable
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) :
    Integrable (S.ξ t i) S.μ := by
  letI := S.prob
  have hξStrong : StronglyMeasurable (S.ξ t i) := by
    simpa [StochasticSteepestDescentGeometryContext.ξ] using
      (S.grad_stronglyMeasurable t).sub ((S.assumption1_sampling.sample_measurable t i).stronglyMeasurable)
  exact integrable_of_sq_integrable hξStrong (S.ξ_sq_integrable t i)

/-- The current iterate is measurable with respect to its prefix filtration. -/
lemma current_iterate_prefixMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ)
    (i : Fin S.batchSize) :
    Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i] (S.W t) := by
  refine Measurable.of_comap_le ?_
  unfold samplePrefixSigma
  exact le_sup_left

/-- Every prefix filtration is a sub-sigma-algebra of the ambient measurable space. -/
lemma samplePrefixSigma_le
    (S : StochasticSteepestDescentGeometryContext Ω V) (t : ℕ)
    (i : Fin S.batchSize) :
    samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i ≤
      inferInstanceAs (MeasurableSpace Ω) := by
  exact samplePrefixSigma_le_of_measurable
    S.batchSize_pos S.W S.stochasticGradientSample
    S.assumption1_sampling.sample_measurable t (S.W_measurable t) i

/-- Earlier iterates are measurable with respect to any later prefix filtration. -/
lemma W_prefixMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s ≤ t) :
    Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (S.W s) := by
  by_cases hEq : s = t
  · subst hEq
    simpa using S.current_iterate_prefixMeasurable s i
  · exact S.W_prefixMeasurable_before t i s (lt_of_le_of_ne hs hEq)

/--
Earlier true gradients are strongly measurable with respect to any later prefix
filtration.
-/
lemma grad_prefixStronglyMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V)
    (t : ℕ) (i : Fin S.batchSize) (s : ℕ)
    (hs : s ≤ t) :
    StronglyMeasurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      (fun ω => S.fGrad (S.W s ω)) := by
  have hWcod :
      Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        (S.constraintBall.codRestrict (S.W s) (S.W_mem_constraintBall s)) := by
    exact Measurable.subtype_mk (S.W_prefixMeasurable t i s hs)
  have hGrad :
      Measurable[samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        (fun ω => S.fGrad (S.W s ω)) := by
    simpa [Function.comp_def, Set.restrict_comp_codRestrict (S.W_mem_constraintBall s)] using
      S.fGrad_restrict_measurable.comp hWcod
  exact hGrad.stronglyMeasurable

/-- The realized stochastic-gradient samples are strongly measurable. -/
lemma sample_stronglyMeasurable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, StronglyMeasurable (S.stochasticGradientSample t i) := by
  intro t i
  exact (S.assumption1_sampling.sample_measurable t i).stronglyMeasurable

/-- Assumption 1 rewritten as a conditional-expectation identity on `iterateSigma`. -/
lemma sample_condexp_eq_grad
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, S.μ[S.stochasticGradientSample t i | S.iterateSigma t] =ᵐ[S.μ] S.grad t := by
  intro t i
  have hIterLePrefix :
      S.iterateSigma t ≤
        samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i := by
    unfold StochasticSteepestDescentGeometryContext.iterateSigma samplePrefixSigma
    exact le_sup_left
  have hPrefixLe :
      samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i ≤
        inferInstanceAs (MeasurableSpace Ω) :=
    S.samplePrefixSigma_le t i
  letI := S.prob
  letI : IsFiniteMeasure S.μ := by infer_instance
  letI : SigmaFinite (S.μ.trim hPrefixLe) := by infer_instance
  have hGradInt : Integrable (S.grad t) S.μ := by
    have hCondInt :
        Integrable
          (S.μ[S.stochasticGradientSample t i |
            samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]) S.μ := by
      simpa using
        (MeasureTheory.integrable_condExp
          (m := samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i)
          (μ := S.μ)
          (f := S.stochasticGradientSample t i))
    exact hCondInt.congr (by
      simpa [StochasticSteepestDescentGeometryContext.grad] using
        S.assumption1_sampling.estimator_condexp_eq_grad_of_prefix S.batchSize_pos t i)
  have hWiter :
      Measurable[S.iterateSigma t]
        (S.constraintBall.codRestrict (S.W t) (S.W_mem_constraintBall t)) := by
    exact Measurable.subtype_mk <| Measurable.of_comap_le <| by
      unfold StochasticSteepestDescentGeometryContext.iterateSigma
      exact le_rfl
  have hGradIter :
      StronglyMeasurable[S.iterateSigma t] (S.grad t) := by
    have hGradMeas :
        Measurable[S.iterateSigma t] (fun ω => S.fGrad (S.W t ω)) := by
      simpa [Function.comp_def, StochasticSteepestDescentGeometryContext.grad,
        Set.restrict_comp_codRestrict (S.W_mem_constraintBall t)] using
        S.fGrad_restrict_measurable.comp hWiter
    exact hGradMeas.stronglyMeasurable
  calc
    S.μ[S.stochasticGradientSample t i | S.iterateSigma t]
      =ᵐ[S.μ]
        S.μ[S.μ[S.stochasticGradientSample t i |
          samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
          | S.iterateSigma t] := by
            exact
              (MeasureTheory.condExp_condExp_of_le
                (μ := S.μ) (f := S.stochasticGradientSample t i)
                hIterLePrefix hPrefixLe).symm
    _ =ᵐ[S.μ] S.μ[S.grad t | S.iterateSigma t] := by
          exact MeasureTheory.condExp_congr_ae <| by
            simpa [StochasticSteepestDescentGeometryContext.grad] using
              S.assumption1_sampling.estimator_condexp_eq_grad_of_prefix S.batchSize_pos t i
    _ =ᵐ[S.μ] S.grad t := by
          exact Filter.EventuallyEq.of_eq
            (MeasureTheory.condExp_of_stronglyMeasurable
              (μ := S.μ)
              (m := S.iterateSigma t)
              (hIterLePrefix.trans hPrefixLe)
              hGradIter
              hGradInt)

/-- Assumption 1 rewritten on the refined prefix filtration. -/
lemma sample_condexp_eq_grad_of_prefix
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t (i : Fin S.batchSize),
      S.μ[S.stochasticGradientSample t i |
          samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        =ᵐ[S.μ] S.grad t := by
  intro t i
  simpa [StochasticSteepestDescentGeometryContext.grad] using
    S.assumption1_sampling.estimator_condexp_eq_grad_of_prefix S.batchSize_pos t i

/-- The true gradient process is integrable at each time. -/
lemma grad_integrable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t, Integrable (S.grad t) S.μ := by
  intro t
  let i : Fin S.batchSize := ⟨0, S.batchSize_pos⟩
  have hCondInt :
      Integrable
        (S.μ[S.stochasticGradientSample t i | S.iterateSigma t]) S.μ := by
    simpa using
      (MeasureTheory.integrable_condExp
        (m := S.iterateSigma t)
        (μ := S.μ)
        (f := S.stochasticGradientSample t i))
  exact hCondInt.congr (by simpa using (S.sample_condexp_eq_grad t i))

/-- The realized stochastic-gradient samples are integrable. -/
lemma sample_integrable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, Integrable (S.stochasticGradientSample t i) S.μ := by
  intro t i
  have hEq :
      S.stochasticGradientSample t i =
        fun ω => S.grad t ω - S.ξ t i ω := by
    funext ω
    simp [StochasticSteepestDescentGeometryContext.ξ, sub_eq_add_neg]
  rw [hEq]
  exact (S.grad_integrable t).sub (S.ξ_integrable t i)

/-- The refined per-sample noises have zero conditional expectation on the prefix filtration. -/
lemma ξ_condexp_eq_zero_of_prefix
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t (i : Fin S.batchSize),
      S.μ[S.ξ t i |
          samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
        =ᵐ[S.μ] 0 := by
  intro t i
  have hPrefixLe :
      samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i ≤
        inferInstanceAs (MeasurableSpace Ω) :=
    S.samplePrefixSigma_le t i
  letI := S.prob
  letI : IsFiniteMeasure S.μ := by
    refine ⟨by simp⟩
  letI : SigmaFinite (S.μ.trim hPrefixLe) := by infer_instance
  have hGradInt : Integrable (S.grad t) S.μ := S.grad_integrable t
  have hSampleInt : Integrable (S.stochasticGradientSample t i) S.μ := S.sample_integrable t i
  have hSub :=
    MeasureTheory.condExp_sub
      (μ := S.μ)
      (m := samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i)
      hGradInt hSampleInt
  calc
    S.μ[S.ξ t i | samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
      =ᵐ[S.μ]
        S.μ[S.grad t | samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i]
          - S.μ[S.stochasticGradientSample t i |
              samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i] := by
            simpa [StochasticSteepestDescentGeometryContext.ξ, Pi.sub_apply] using hSub
    _ =ᵐ[S.μ]
        S.grad t
          - S.μ[S.stochasticGradientSample t i |
              samplePrefixSigma S.batchSize_pos S.W S.stochasticGradientSample t i] := by
            refine Filter.EventuallyEq.sub ?_ Filter.EventuallyEq.rfl
            simpa using
              (Filter.EventuallyEq.of_eq
                (MeasureTheory.condExp_of_stronglyMeasurable
                  hPrefixLe
                  (S.grad_prefixStronglyMeasurable t i t le_rfl)
                  hGradInt))
    _ =ᵐ[S.μ] 0 := by
            filter_upwards [S.sample_condexp_eq_grad_of_prefix t i] with ω hω
            simp [hω]

/-- The per-sample noise second moment is integrable. -/
private lemma second_moment_integrable
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, Integrable (fun ω => ‖S.ξ t i ω‖ ^ 2) S.μ := by
  intro t i
  exact S.ξ_sq_integrable t i

/-- The conditional second moment of the per-sample noise is uniformly bounded. -/
lemma sample_cond_secondMoment_le
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i,
      S.μ[fun ω => ‖S.ξ t i ω‖ ^ 2 | S.iterateSigma t] ≤ᵐ[S.μ]
        fun _ => S.sigma ^ 2 := by
  intro t i
  simpa [StochasticSteepestDescentGeometryContext.iterateSigma,
    StochasticSteepestDescentGeometryContext.ξ,
    StochasticSteepestDescentGeometryContext.grad,
    StochasticSteepestDescentGeometryContext.sigma] using
    S.assumption2_secondMoment.cond_secondMoment_le t i

/-- Uniform second-moment bound for the per-sample gradient noise. -/
lemma second_moment_bound
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i,
      Integrable (fun ω => ‖S.ξ t i ω‖ ^ 2) S.μ ∧
        ∫ ω, ‖S.ξ t i ω‖ ^ 2 ∂S.μ ≤ S.sigma ^ 2 := by
  intro t i
  constructor
  · exact S.second_moment_integrable t i
  · have hCondInt :
        Integrable
          (S.μ[fun ω => ‖S.ξ t i ω‖ ^ 2 | S.iterateSigma t]) S.μ := by
      simpa using
        (MeasureTheory.integrable_condExp
          (m := S.iterateSigma t)
          (μ := S.μ)
          (f := fun ω => ‖S.ξ t i ω‖ ^ 2))
    letI := S.prob
    have hConst :
        Integrable (fun _ : Ω => S.sigma ^ 2) S.μ :=
      MeasureTheory.integrable_const _
    have hMono :
        ∫ ω, S.μ[fun ω => ‖S.ξ t i ω‖ ^ 2 | S.iterateSigma t] ω ∂S.μ ≤
          ∫ ω, S.sigma ^ 2 ∂S.μ := by
      exact
        MeasureTheory.integral_mono_ae hCondInt hConst
          (S.sample_cond_secondMoment_le t i)
    have hIterateSigma :
        S.iterateSigma t ≤ inferInstanceAs (MeasurableSpace Ω) := by
      simpa [StochasticSteepestDescentGeometryContext.iterateSigma] using
        (S.W_measurable t).comap_le
    calc
      ∫ ω, ‖S.ξ t i ω‖ ^ 2 ∂S.μ
        = ∫ ω, S.μ[fun ω => ‖S.ξ t i ω‖ ^ 2 | S.iterateSigma t] ω ∂S.μ := by
            symm
            exact
              MeasureTheory.integral_condExp
                (m := S.iterateSigma t)
                (μ := S.μ)
                (f := fun ω => ‖S.ξ t i ω‖ ^ 2)
                hIterateSigma
      _ ≤ ∫ ω, S.sigma ^ 2 ∂S.μ := hMono
      _ = S.sigma ^ 2 := by simp

/-- The per-sample gradient noise has zero mean. -/
lemma sample_mean_zero
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, ∫ ω, S.ξ t i ω ∂S.μ = 0 := by
  intro t i
  have hGradInt : Integrable (S.grad t) S.μ := S.grad_integrable t
  have hSampleInt : Integrable (S.stochasticGradientSample t i) S.μ := S.sample_integrable t i
  have hEq :
      ∫ ω, S.grad t ω ∂S.μ = ∫ ω, S.stochasticGradientSample t i ω ∂S.μ := by
    letI := S.prob
    have hIterateSigma :
        S.iterateSigma t ≤ inferInstanceAs (MeasurableSpace Ω) := by
      simpa [StochasticSteepestDescentGeometryContext.iterateSigma] using
        (S.W_measurable t).comap_le
    calc
      ∫ ω, S.grad t ω ∂S.μ
        = ∫ ω, S.μ[S.stochasticGradientSample t i | S.iterateSigma t] ω ∂S.μ := by
            refine integral_congr_ae ?_
            simpa using (S.sample_condexp_eq_grad t i).symm
      _ = ∫ ω, S.stochasticGradientSample t i ω ∂S.μ := by
            exact
              MeasureTheory.integral_condExp
                (m := S.iterateSigma t)
                (μ := S.μ)
                (f := S.stochasticGradientSample t i)
                hIterateSigma
  calc
    ∫ ω, S.ξ t i ω ∂S.μ
      = ∫ ω, S.grad t ω ∂S.μ - ∫ ω, S.stochasticGradientSample t i ω ∂S.μ := by
          simp [StochasticSteepestDescentGeometryContext.ξ,
            MeasureTheory.integral_sub hGradInt hSampleInt]
    _ = 0 := sub_eq_zero.mpr hEq

/-- Assumption 4 rewritten as a bound on the raw samplewise gradient error. -/
lemma oracle_sample_norm_le_noiseRadius_ae
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, ∀ᵐ ω ∂S.μ, ‖S.grad t ω - S.stochasticGradientSample t i ω‖ ≤ S.noiseRadius := by
  intro t i
  simpa [StochasticSteepestDescentGeometryContext.grad,
    StochasticSteepestDescentGeometryContext.noiseRadius] using
    S.assumption4_oracleSampleNoiseBound t i

/-- The refined per-sample noise is almost surely supported in the Assumption-4 radius. -/
lemma sample_norm_le_noiseRadius_ae
    (S : StochasticSteepestDescentGeometryContext Ω V) :
    ∀ t i, ∀ᵐ ω ∂S.μ, ‖S.ξ t i ω‖ ≤ S.noiseRadius := by
  intro t i
  simpa [StochasticSteepestDescentGeometryContext.ξ,
    StochasticSteepestDescentGeometryContext.grad,
    StochasticSteepestDescentGeometryContext.noiseRadius] using
    S.oracle_sample_norm_le_noiseRadius_ae t i

end PublicTheorems

end StochasticSteepestDescentGeometryContext

end

end SteepestDescentOptimizationBounds
